### ISSUE TITLE
Bundle staged for too long

### ISSUE THREAD

**Issue by tbright17** [codalab/codalab-worksheets#1146] opened 2019-05-16 19:15 UTC
Hi,
I have a bundle https://worksheets.codalab.org/bundles/0xcdec33d52f594f65b0f2f084bc54760a that has been in staged status for very long time. Both my disk and time quota are enough. What could be the reason?

Thanks

**Comment by Matt-F-Wu** [comment] 2019-05-16 19:59
Hi, is this bundle still staged? It was likely just because we had high service volume before.

**Comment by tbright17** [comment] 2019-05-16 20:38
> Hi, is this bundle still staged? It was likely just because we had high service volume before.

Yes. It's still staged.

**Comment by tbright17** [comment] 2019-05-16 20:40
> Hi, is this bundle still staged? It was likely just because we had high service volume before.

Oh actually I deleted it and restarted a new bundle. It's also staged. My collaborator also started a run bundle same as mine, and it's also staged. Did you mean they are in waiting list?

**Comment by bkgoksel** [comment] 2019-05-16 20:52
Hi, we're still under high load, so your bundles are still waiting for compute resources to free up.

**Comment by tbright17** [comment] 2019-05-16 20:58
> Hi, we're still under high load, so your bundles are still waiting for compute resources to free up.

Thanks for the reply. Is there an estimated time when my job can start running?

**Comment by WSTC2007** [comment] 2019-05-28 06:45
> > Hi, we're still under high load, so your bundles are still waiting for compute resources to free up.
> 
> Thanks for the reply. Is there an estimated time when my job can start running?

Hi, I meet the same question as you. Have your job start running? How long did you wait?

**Comment by bkgoksel** [comment] 2019-06-05 21:05
Closing as workers have freed up.

**Closed as completed by bkgoksel** 2019-06-05 21:05 UTC
Labels: user-question

**Comment by SimonOst** [comment] 2019-06-12 12:34
I also have that problem right now, for almost 2 days - are the workers still busy?

**Comment by adamsZQ** [comment] 2019-06-12 12:37
sorry, but I have the same problem, and my collaborator also told me that their bundles are also staged.

**Comment by SimonOst** [comment] 2019-06-13 07:48
The problem is getting a bit more pressing right now, since we are starting the eval phase for a shared task for an EMNLP workshop tomorrow, using Codalab. Can anybody please confirm that this is looked after or that it will resolve itself?

**Comment by percyliang** [comment] 2019-06-13 15:40
See https://github.com/codalab/codalab-worksheets/wiki/FAQ#why-is-my-run-bundle-in-staged-for-a-long-time
We will try to bring up more workers soon, but is it possible for you to hook up your own machines in the meantime to ease the load?

**Comment by SimonOst** [comment] 2019-06-14 09:38
Thanks for getting back to us! As of now, everything seems to work again - thanks anyways.
