### ISSUE TITLE
[USER ISSUE] cl uinfo's display is broken in worksheets.codalab.org

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1492] opened 2019-10-09 21:43 UTC
**Describe the bug**
Type `cl uinfo ZhengQuan`, the web page doesn't return the correct information. Instead, it throws some js error:

**Codalab Information**
- *Error message received from Codalab (if applicable)*:
```
[USER]: https://worksheets.codalab.org/static/js/main.00221ff2.chunk.js: this.props.ws.info is null
value@https://worksheets.codalab.org/static/js/main.00221ff2.chunk.js:1:38298
value/this.terminal<@https://worksheets.codalab.org/static/js/main.00221ff2.chunk.js:1:36277
x/c<@https://worksheets.codalab.org/static/js/1.5b94faa8.chunk.js:1:252055
x@https://worksheets.codalab.org/static/js/1.5b94faa8.chunk.js:1:252215
ENTER@https://worksheets.codalab.org/static/js/1.5b94faa8.chunk.js:1:186813
kt@https://worksheets.codalab.org/static/js/1.5b94faa8.chunk.js:1:200857
dispatch@https://worksheets.codalab.org/static/js/1.5b94faa8.chunk.js:1:42687
add/m.handle@https://worksheets.codalab.org/static/js/1.5b94faa8.chunk.js:1:40699
```
 - *Browser (if on Web)*; Firefox and Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Go to worksheets.codalab.org, login to your account
2. Click on CLI on the webpage
3. Type `cl uinfo ZhengQuan`

**Expected behavior**
It throws errors as I mentioned above.

**Screenshots**
<img width="1291" alt="Screen Shot 2019-10-09 at 9 42 09 AM" src="https://user-images.githubusercontent.com/1483372/66522350-120db300-eaa2-11e9-9e7c-088c9a39e748.png">

**Comment by Levilian** [comment] 2019-10-09 21:46
<img width="1242" alt="Screen Shot 2019-10-09 at 2 45 21 PM" src="https://user-images.githubusercontent.com/13169407/66522950-7715d880-eaa3-11e9-961a-e683f9ef0035.png">

**Comment by percyliang** [comment] 2019-11-12 19:41
Can't reproduce, closing.

**Closed as completed by percyliang** 2019-11-12 19:41 UTC
Labels: bug
