### ISSUE TITLE
[no such file or directory] when my data is uploaded correct

### ISSUE THREAD

**Issue by Faris-ML** [codalab/codalab-worksheets#3681] opened 2021-07-07 07:37 UTC
i am trying to training on images and every time i face this error, but when i rerun the training the error happend in diffrent image.
it seams that some times the bundle get blind for a second.
traceback error :

Traceback (most recent call last):
  File "/0x8a2363e3fb9e40d8bf3ac7989d62b657/train.py", line 86, in <module>
    history = model.fit(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 1131, in fit
    val_logs = self.evaluate(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 1389, in evaluate
    tmp_logs = self.test_function(iterator)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError:  data_faris/data_faris/val/iii/b34f0520-ce5d-11eb-b317-38f9d35ea60f.png; No such file or directory
	 [[{{node ReadFile}}]]
	 [[IteratorGetNext]] [Op:__inference_test_function_4460]

Function call stack:
test_function

**Comment by epicfaace** [comment] 2021-07-07 12:10
Can you add a link to the bundle?

**Comment by epicfaace** [comment] 2021-07-07 12:32
@Faris-ML I think the workers that were running a couple of hours ago were outdated and didn't have the fix. Can you try running the bundle again and let me know if the issue is still occurring?

**Comment by Faris-ML** [comment] 2021-07-07 14:21
I try to re run it many times until its work
Because its crash in random files
If its occur again i will send you the crashed bundle link

**Comment by epicfaace** [comment] 2021-07-07 23:02
Sounds good -- I'm going to close this, but feel free to re-open if you see this issue again.

**Closed as completed by epicfaace** 2021-07-07 23:02 UTC
Labels: user-question

**Comment by Faris-ML** [comment] 2021-07-07 23:19
Ok, thank you
