### ISSUE TITLE
Merge bundle details page code with side panel code

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#21] opened 2015-12-27 10:10 UTC
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Tuesday Oct 20, 2015 at 04:10 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1346_

----

Side panel is currently the official way to display bundle information.  For the bundle details page, just call the side panel code (might have to customize the formatting a bit).

**Comment by kashizui** [comment] 2016-02-04 08:52
@percyliang I thought we decided we would keep the bundle details page?

**Comment by percyliang** [comment] 2016-02-04 15:51
Yes.  But the code and interface should be shared between the two.

**Comment by kashizui** [comment] 2016-02-08 01:16
Got it!

**Comment by kashizui** [comment] 2016-05-19 07:52
Duplicate of #159

**Closed by kashizui** 2016-05-19 07:52 UTC
Labels: P1
