### ISSUE TITLE
modify job priorities to ensure fairness

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#239] opened 2015-11-17 16:24 UTC
Two things:

1) Users should be able to change the priority of their jobs.

2) The system needs to be able to normalize the priority of users' jobs based on their resource usage to ensure fairness.

Either way, we need to modify dispatch-torque and dispatch-q to be able to change the priority of jobs, so that if someone launches 1000 jobs and they're all queued, someone else can intercept.

**Comment by percyliang** [comment] 2015-11-22 21:28
Here's a simple heuristic:
- At any point in time, each user has a priority (integer).
- There is a set of runs that have been submitted by the users but not run yet (these are the queued runs).  Set the priority of the runs based on the user's priority.
- If a user's bundle gets executed, then we decrement that user's priority.  When the user's job finishes, the priority gets incremented.

**Comment by bkgoksel** [comment] 2019-03-20 22:43
Duplicate of #1047

**Closed as completed by bkgoksel** 2019-03-20 22:43 UTC
