### ISSUE TITLE
Test performance

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#182] opened 2015-10-21 05:31 UTC
Put together automated tests to get an idea of the performance of the bundle service, and also general stress testing.

**Comment by percyliang** [comment] 2015-11-22 20:55
The goal is to get an idea of the number of people that can simultaneously use CodaLab without a noticeable degradation in performance.

**Comment by percyliang** [comment] 2015-12-29 06:21
We should have an automatic way of benchmarking this so we can monitor this metric.

**Comment by percyliang** [comment] 2017-02-04 22:48
Duplicate of #632

**Closed as completed by percyliang** 2017-02-04 22:48 UTC
