### ISSUE TITLE
Can't download image: 404 Client Error: Not Found ("no such image: 

### ISSUE THREAD

**Issue by lrh000** [codalab/codalab-worksheets#1098] opened 2019-03-15 09:13 UTC
I have my own docker image on docker Hub, but cannot download it on codalab. It worked a month ago. Why?

**Comment by bkgoksel** [comment] 2019-03-19 06:02
Hi, could you 
1-) Share your username
2-) Share the worksheet and bundle UUIDs for the failing bundles
3-) Share the name of the docker image.

We've done some maintenance work on the worker machines recently, so trying again might just fix your problem as well.

**Comment by lrh000** [comment] 2019-03-20 15:28
> 
> 
> Hi, could you
> 1-) Share your username
> 2-) Share the worksheet and bundle UUIDs for the failing bundles
> 3-) Share the name of the docker image.
> 
> We've done some maintenance work on the worker machines recently, so trying again might just fix your problem as well.

@bkgoksel Hi, my username is lrh000, and worksheet UUID is 0xd7a14d1a5fed49dd812067a23f07b470, and my docker image is lrh000/ubuntu:nlp.
Today I tried again, succeeding twice and failing last time. The bundle UUID is 0xa151992f849248fe9d3241aac98d61fc.
Any mistake did I have? Thanks.

**Comment by lrh000** [comment] 2019-03-20 15:37
> 
> 
> > Hi, could you
> > 1-) Share your username
> > 2-) Share the worksheet and bundle UUIDs for the failing bundles
> > 3-) Share the name of the docker image.
> > We've done some maintenance work on the worker machines recently, so trying again might just fix your problem as well.
> 
> @bkgoksel Hi, my username is lrh000, and worksheet UUID is 0xd7a14d1a5fed49dd812067a23f07b470, and my docker image is lrh000/ubuntu:nlp.
> Today I tried again, succeeding twice and failing last time. The bundle UUID is 0xa151992f849248fe9d3241aac98d61fc.
> Any mistake did I have? Thanks.

@bkgoksel Oh, it works again, which seems a little unstable. I retain the failed one if you need check it. Thank you anyway.

**Comment by bkgoksel** [comment] 2019-03-20 20:53
Hi @lrh000, there was a disk issue on one particular machine that your run got assigned to which is fixed now. Thanks for bringing this to our attention. We just made a patch to avoid similar issues in the future. 
Closing this issue now as the root cause seems to be fixed. 
Let us know if you run into any other issues.

Kerem

**Closed as completed by bkgoksel** 2019-03-20 20:53 UTC
