### ISSUE TITLE
[USER ISSUE] Uploading from CLI gets stucked locally even after the job is finished

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#2054] opened 2020-03-03 01:05 UTC
**Describe the bug**
I was trying to upload a bundle with a size 895m from CLI. The uploading process went well at the beginning. However, after uploaded 785m, the progress bar stopped updating from CLI. In around 30 minutes, I refreshed the bundle from the Web UI [(0xc3240400cdf540818bf8203ff296d4bf)](https://worksheets.codalab.org/worksheets/0xc3240400cdf540818bf8203ff296d4bf), the bundle status has already been marked with uploaded successfully. I had to manually kill the process to free the bash shell.

**Codalab Information**
- *Your username*:
- *UUID of worksheet where the problem occurred*:0xc3240400cdf540818bf8203ff296d4bf
- *UUID of problem bundle (please don't delete)*:0x2a6b87f8432e4dd3883b140be38ac6e4
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*: Mac OS Mojave 10.14.6
 - *Codalab CLI Version (if on CLI)*: v0.5.9
 - *Browser (if on Web)*; Chrome

**Expected behavior**
The current foreground process should terminate automatically. 

**Screenshots**
<img width="946" alt="Screen Shot 2020-03-02 at 4 52 59 PM" src="https://user-images.githubusercontent.com/1483372/75732367-264b8a00-5ca7-11ea-9a12-4c56c0ffe41f.png">

**Comment by Levilian** [comment] 2020-03-05 09:04
Since it's CLI based and the file is actually uploaded successfully, does that mean it's your Internet problem and not with CodaLab?

**Comment by percyliang** [comment] 2020-06-21 17:11
How reproducible is this bug?

**Comment by percyliang** [comment] 2020-07-01 20:41
Closing for now, re-open if can reproduce.

**Closed as completed by percyliang** 2020-07-01 20:41 UTC
Labels: bug
