### ISSUE TITLE
Dependencies sometimes fail to mount

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2723] opened 2020-08-07 19:16 UTC
This bundle failed because it failed to find a script in a dependency at the path that it expects: https://codalab.stanford.edu/bundles/0xf8b9bd36e8bd4d8ead256f168a2c42b3

However, mimic-ing the bundle led to success: https://codalab.stanford.edu/bundles/0xdaffe96a8cfa409ebd1f35197b5623c2

It seems like sometimes, dependencies aren't being mounted properly?

**Comment by yiboliu** [comment] 2020-08-08 05:47
Wasn't able to view this, since I don't have access

**Comment by percyliang** [comment] 2020-08-09 22:05
How reproducible is this?

**Comment by nelson-liu** [comment] 2020-08-09 22:27
i haven't put much effort into reproducing it, but it doesn't happen _that_ often.

**Comment by nelson-liu** [comment] 2020-08-15 22:39
I think this is related to #1417 , so I'm going to link them. In this bundle ( https://codalab.stanford.edu/bundles/0x28e3f9b40be745acad20c7cb448b0b66 ), I run:

```
python dependency/script.py ; python dependency/script.py 
```

The first invocation works without any issues, but on the second one, python complains that `dependency/script.py` doesn't exist.

**Comment by percyliang** [comment] 2020-08-20 21:13
Seems like it happens more when using worksheets.codalab.org with NLP workers?

**Comment by epicfaace** [comment] 2021-07-04 22:01
Closing in favor of https://github.com/codalab/codalab-worksheets/issues/3627.

**Closed as completed by epicfaace** 2021-07-04 22:01 UTC
Labels: bug, user-question, backend, p3
