### ISSUE TITLE
BundleManager sometimes stalls for a very long time (~1 hour)

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2423] opened 2020-06-18 00:44 UTC
**Describe the bug**

Sometimes, the BundleManager appears unresponsive for a very long time. New runs are not staged or assigned to run on workers and dead workers are not cleaned up.

This is running on the latest master branch.

After investigating, I figured out that the BundleManager isn't stuck--it simply takes an inordinate amount of time to try to schedule each bundle. In `BundleManager._schedule_run_bundles_on_workers`, we iterate through the staged bundles and try to start them on each of the workers that have the resources to take the bundle (https://github.com/codalab/codalab-worksheets/blob/master/codalab/server/bundle_manager.py#L386).

However, sometimes a worker goes offline in this process (this happens with the SlurmWorkerManager, when a worker gets pre-empted [1]). As a result, we have to iterate through *every bundle* and try to run it on a worker that's offline. This can take a large amount of time, upwards of an hour. This is bad because no bundles are staged for an hour+, which also means that new workers won't pick up jobs and might exit (if they have `--exit-on-idle` set to true).

[1]: I think there's an especially bad interaction with the `SlurmWorkerManager` and the restage-on-terminate feature—this issue always comes up when a job is pre-empted.

**Comment by candicegjing** [comment] 2020-06-18 17:51
One naive solution to solve this problem is to add another column to the `worker` table, e.g. `is_terminating: bool`. This column will act as a flag which indicates if the worker is going to be terminated soon. 
On the bundle manager side, it can check if the `is_terminating` column is `True` before it starts to actually dispatch a bundle to a worker. _However, the downside is that this approach introduces some performance overhead in dispatching logic, although the `worker` table is small._ Another thing is that if the worker goes offline due to other reasons rather than _pre-emption_, this approach probably won't help much. However, for the worker offline issue due to pre-emption, this approach should be able to handle real use cases.

**Comment by nelson-liu** [comment] 2020-06-18 17:52
> Another thing is that if the worker goes offline due to other reasons rather than pre-emption, this approach probably won't help much.

Yeah, this is my main worry and why i went with #2424...it feels like it provides the greatest coverage.

**Comment by epicfaace** [comment] 2020-06-18 17:58
Might this be causing #2388?

**Comment by nelson-liu** [comment] 2020-06-18 18:08
Hmm, in #2388, we only have 1 bundle staged and 1 worker connected, right? This slowdown only starts becoming an issue when we have a large number of bundles (there are around 10K on an instance). Back of the envelope calculations have each loop iteration taking 0.5 seconds.

Maybe I'm missing some context on #2388, but it's referring to the issue that in CI, it can be slow to start a new run (e.g., it hangs for awhile on the `cl wait`). If that's the case, I'm not super sure that this is the culprit. I have noticed that same 10-minute gap when testing locally, but I always assumed that it was just taking a long time to download the `default-cpu` image.

**Comment by candicegjing** [comment] 2020-06-18 18:13
I don't think this issue is related to #2388, because we don't use the pre-emption mode in our Git Action tests. Plus worker offline doesn't happen too often in our tests?

**Comment by candicegjing** [comment] 2020-06-18 19:43
To summarize:

There are essentially two issues here:
1. The bundle manager keeps assigning bundles to a worker that is going to be terminated soon.
    1. a bundle that is assigned to a terminating worker will stay in the `starting` state for 5 minutes until it gets picked up by the bundle manager.
    1. after the `starting` bundle gets picked up by the bundle manager, the worker goes offline, but there is still a record of this offline worker in the database.
1. The bundle manager keeps assigning bundles to a worker that is offline. (worker is disconnected, but its record still exists in the database)

Based on the above summary, there are differences and overlap between 1 and 2:
1. overlap: 1.ii and 2.
     1. goal: minimize the number of bundles that will be assigned to **an offline** worker.
     1. approach: detect _the offline worker_ before dispatching a bundle.
1. difference: 1.a 
     1. goal: minimize the number of bundles that will be assigned to **a terminating** worker. 
     1. approach: detect _the terminating worker_ before dispatching a bundle.

**Comment by nelson-liu** [comment] 2020-06-20 20:04
I'm currently seeing this on the main instance:
```
CodaLab> cl workers
worker_id                                          cpus  gpus  memory  free_disk  last_checkin  tag     runs      shared_file_system  tag_exclusive
---------------------------------------------------------------------------------------------------------------------------------------------------
nfliu-codalab-slurm-worker-main-standard-0ba9aa51  3/4   1/1   125g    747g       0.0s ago      nlpgpu  0xad1ebc  False               False        
nfliu-codalab-slurm-worker-main-standard-4dd7cd2c  0/4   0/1   125g    737g       11m35s ago    nlpgpu            False               False        
nfliu-codalab-slurm-worker-main-standard-7ef933b0  3/4   1/1   125g    614g       2.0s ago      nlpgpu  0x728e81  False               False        
nfliu-codalab-slurm-worker-main-standard-b20a382a  3/4   1/1   125g    783g       13m6s ago     nlpgpu  0xbe9abc  False               False        
nfliu-codalab-slurm-worker-main-standard-be8ee085  3/4   1/1   125g    737g       1.0s ago      nlpgpu  0x6e5c88  False               False        
nfliu-codalab-slurm-worker-main-standard-fb631ad4  0/4   0/1   125g    747g       0.0s ago      nlpgpu            False               False        
nfliu-codalab-slurm-worker-main-standard-fd6d8bdc  0/4   0/1   125g    786g       2.0s ago      nlpgpu            False               False
```

Note that some of these workers have very long timeout values, since they're offline (and haven't been cleaned up yet)

**Comment by nelson-liu** [comment] 2020-06-20 20:09
@candicegjing while I agree that `1.a: minimize the number of bundles that will be assigned to a worker which will be terminating soon.` is a problem, in practice, I haven't actually seen this happen much...the 5 minute delay doesn't bother me. It's also a bit problematic since we can't necessarily reliably detect when a worker is terminating (e.g., if it's killed without a signal). Besides, isn't this exactly what the 5 minute restage is for? At a broader level, this issue only affects 1 bundle, and fixes itself after 5 minutes, so I'm not too worried.

I think that `minimize the number of bundles that will be assigned to an offline worker` will have a much greater impact, and do a lot more to fix this issue, since this issue affects _all_ bundles and _all_ workers, and takes a long time to fix itself.

**Comment by candicegjing** [comment] 2020-06-22 18:12
> @candicegjing while I agree that `1.a: minimize the number of bundles that will be assigned to a worker which will be terminating soon.` is a problem, in practice, I haven't actually seen this happen much...the 5 minute delay doesn't bother me. It's also a bit problematic since we can't necessarily reliably detect when a worker is terminating (e.g., if it's killed without a signal). Besides, isn't this exactly what the 5 minute restage is for? At a broader level, this issue only affects 1 bundle, and fixes itself after 5 minutes, so I'm not too worried.

`1.a` documented in https://github.com/codalab/codalab-worksheets/issues/2423#issuecomment-646269225 will definitely be a problem once you have tons of bundles in the scheduling queue, as the `cleanup_dead_worker` will be much less frequently done. Basically, `1.a` will be trouble sooner or later once the server has more active bundles in the future. With a longer period of time before cleaning up dead workers, bundles will be kept dispatching to a worker that is already stopped accepting any new runs. After they got stuck in the `starting` state,  the desired order of bundles execution is messed up. Although, we might not be able to catch every single case when a worker is terminating (e.g. a SIGKILL is triggered), but I still want to do the best we can to ensure the jobs will be scheduled in the order user-preferred. 

It's great that you tried to put up a fix for `2`. But I think we do need to get `1` fixed as well. Maybe to further differentiate these two issues, I am creating another ticket to track each of them https://github.com/codalab/codalab-worksheets/issues/2485

**Comment by nelson-liu** [comment] 2020-06-22 18:26
Ok, that sounds good—for the reference, there are `9216` staged bundles on codalab.stanford.edu right now, but I don't think I've seen the issue you mention...maybe I'm not looking close enough.

**Comment by candicegjing** [comment] 2020-06-22 20:45
> Ok, that sounds good—for the reference, there are `9216` staged bundles on codalab.stanford.edu right now, but I don't think I've seen the issue you mention...maybe I'm not looking close enough.

That's interesting... What I am seeing in my local testings is that once my worker (with `--pass-down-termination` set) gets terminated, my queued jobs are randomly toggled between the `staged` state to the `starting` state for a period of time before they stay at the `staged` state... 
I'll double-check this and see if we can do a better job at ensuring job priority.

**Comment by candicegjing** [comment] 2020-06-24 22:00
Just did more investigation on this issue. 
To reproduce this issue, I created 3300 staged bundles on our dev environment. Benchmarking result shows that on the main loop level, it takes around 5 seconds for those 3300 staged bundles to go through all the steps including cleaning up dead workers,  schedule run bundles, etc. The main dispatching loop (schedule_run_bundles) only takes around 2.5 seconds to complete scheduling those many staged bundles and should be quick enough to reach the cleanup dead worker logic. Since the problematic workers mentioned in https://github.com/codalab/codalab-worksheets/issues/2423#issuecomment-647039876 didn't check in for over 10 minutes and hasn't been picked up by the clean up dead worker logic, I wonder if there is something wrong on the worker side, or I missed some important details, as this situation doesn't seem to be possible based on my benchmark results. Please let me know if I missed any non-trivial details.

**Comment by nelson-liu** [comment] 2020-06-24 23:26
Ok, here's a repro. Everything is on latest master:

0. Checkout the latest master. HEAD is `9cf494b7`

```
git checkout master
```

1. Apply the following patch (https://gist.github.com/nelson-liu/46e9dd4b8b378282142c3f103f6d5c96). It adds some extra logging, and changes the default request-memory to 500mb (since my macbook doesn't have enough ram to run bundles with the default 2g)

```
wget https://gist.githubusercontent.com/nelson-liu/46e9dd4b8b378282142c3f103f6d5c96/raw/b27236a3d8c83aa7ba7c254c7f6dbacef01e7540/bundle_manager_extra_logging.diff
git apply bundle_manager_extra_logging.diff
```

2. Start up a local codalab instance:
```
python3.6 codalab_service.py start --build-images --service mysql nginx frontend rest-server bundle-manager init monitor
```

3. Open a new terminal tab, and check the docker logs. You should see a bunch of logging as the bundlemanger goes through its motions. You can just leave this open, it'll auto refresh:

```
docker logs codalab_bundle-manager_1 --tail 100 -f

2020-06-24 23:14:14,821 _stage_bundles()
2020-06-24 23:14:14,841 Staging 0xc73df633d7b34d25a369dec07caac4c4
2020-06-24 23:14:14,845 Staging 0xc6ac693cd14440caa78bfa3b7a47ae0b
2020-06-24 23:14:14,849 Staging 0x26ef916879154d7e878f04f3a0637570
2020-06-24 23:14:14,852 Done _stage_bundles()
2020-06-24 23:14:14,852 _make_bundles()
2020-06-24 23:14:14,857 Done _make_bundles()
2020-06-24 23:14:14,858 _schedule_run_bundles()
2020-06-24 23:14:14,862 _cleanup_dead_workers()
2020-06-24 23:14:14,862 Done _cleanup_dead_workers()
...etc...
```

4. Stage a bunch of bundles. You don't have to wait for this to finish:

```
for i in {1..5000}; do cl run "sleep 60" -w http://localhost::home-codalab; done
```

5. Open a new terminal tab, run a worker. I set the worker id to a random uuid:

```
cl-worker --server http://localhost --work-dir ./worker_scr  --pass-down-termination --delete-work-dir-on-exit --verbose --id=$(uuidgen)
```

6. It should start picking up bundles. Wait until it starts running some things.

7. KeyboardInterrupt the worker (Ctrl+C). Equivalently, this could be a slurm pre-emption, or anything else that causes the worker to terminate:

```
2020-06-24 16:18:06,538 http://localhost:None "GET /v1.35/containers/4f16e4cdd59de0c7f0feef199e9d47c43a2b9599ca0d1434365870959ce918c9/json HTTP/1.1" 200 None
2020-06-24 16:18:06,544 http://localhost:None "GET /v1.35/containers/4f16e4cdd59de0c7f0feef199e9d47c43a2b9599ca0d1434365870959ce918c9/json HTTP/1.1" 200 None
2020-06-24 16:18:06,551 http://localhost:None "GET /v1.35/containers/4f16e4cdd59de0c7f0feef199e9d47c43a2b9599ca0d1434365870959ce918c9/json HTTP/1.1" 200 None
^C2020-06-24 16:18:09,685 Sending bundles back to the staged state: 0x80653288d1a54bc9a3027dde219fa21d,0x30106aabc4ec435e89b2493202bd324f.
2020-06-24 16:18:09,691 http://localhost:None "GET /v1.35/containers/4f16e4cdd59de0c7f0feef199e9d47c43a2b9599ca0d1434365870959ce918c9/json HTTP/1.1" 200 None
......output goes on here.........
2020-06-24 16:18:16,006 Stopping Worker
2020-06-24 16:18:16,006 Stopping docker image manager
2020-06-24 16:18:16,007 Stopping docker image manager: stop the downloads threads
2020-06-24 16:18:16,007 Stopped docker image manager
2020-06-24 16:18:16,007 Stopping local dependency manager
2020-06-24 16:18:16,239 Stopped local dependency manager
2020-06-24 16:18:16,276 http://localhost:None "DELETE /v1.35/networks/ca82774eeb2797eb895c4092ac3e8e4f671a84af2f3d7329f3456004dc834109 HTTP/1.1" 204 0
2020-06-24 16:18:16,312 http://localhost:None "DELETE /v1.35/networks/3415d4efd6f9b8f3b2e143fdf047078e5d75531708a29d36b5f5ebbd508699b5 HTTP/1.1" 204 0
2020-06-24 16:18:16,381 http://localhost:None "DELETE /v1.35/networks/cb4a4bcdc899d40416c73fe155f9cbd80b5123173b5bf314fdf1a4f38df54429 HTTP/1.1" 204 0
2020-06-24 16:18:16,382 Stopped Worker. Exiting
```

8. If you look at the BundleManager logs in docker, you should see:

```
2020-06-24 23:18:14,193 Dispatching bundle 0x1e397ea2341747eb936333cacc3a3320
2020-06-24 23:18:14,193 Dispatching bundle 0x8b63f0b30fa14a64ad4883f0e2289ff0
2020-06-24 23:18:14,197 Done _schedule_run_bundles()
2020-06-24 23:18:14,197 _fail_unresponsive_bundles()
2020-06-24 23:18:14,603 Done _fail_unresponsive_bundles()
2020-06-24 23:18:15,104 _stage_bundles()
2020-06-24 23:18:15,122 Staging 0x69abb68455b440ca98c9db08685dd6ce
2020-06-24 23:18:15,124 Staging 0x4955fbe86e22409884a404567bbd075e
2020-06-24 23:18:15,127 Staging 0x113a99dcf7f2474fb887577a41ddd95a
2020-06-24 23:18:15,130 Done _stage_bundles()
2020-06-24 23:18:15,130 _make_bundles()
2020-06-24 23:18:15,135 Done _make_bundles()
2020-06-24 23:18:15,136 _schedule_run_bundles()
2020-06-24 23:18:15,139 _cleanup_dead_workers()
2020-06-24 23:18:15,139 Done _cleanup_dead_workers()
2020-06-24 23:18:15,139 _restage_stuck_starting_bundles()
2020-06-24 23:18:15,142 Done _restage_stuck_starting_bundles()
2020-06-24 23:18:15,142 _bring_offline_stuck_running_bundles
2020-06-24 23:18:15,146 Done _bring_offline_stuck_running_bundles
2020-06-24 23:18:15,146 _acknowledge_recently_finished_bundles()
2020-06-24 23:18:15,149 Done _acknowledge_recently_finished_bundles()
^[[B2020-06-24 23:18:15,993 Dispatching bundle 0x80653288d1a54bc9a3027dde219fa21d
2020-06-24 23:18:15,993 Attempting to dispatch bundle 0x80653288d1a54bc9a3027dde219fa21d on 1068269C-A4E6-400F-A427-D2251BC9F780
2020-06-24 23:18:16,003 Starting run bundle 0x80653288d1a54bc9a3027dde219fa21d on worker 1068269C-A4E6-400F-A427-D2251BC9F780
2020-06-24 23:18:16,003 Dispatching bundle 0x660aed4c9ce84ef0b9f4934d9706b37a
2020-06-24 23:18:16,004 Attempting to dispatch bundle 0x660aed4c9ce84ef0b9f4934d9706b37a on 1068269C-A4E6-400F-A427-D2251BC9F780
2020-06-24 23:18:16,319 Dispatching bundle 0x30106aabc4ec435e89b2493202bd324f
2020-06-24 23:18:16,319 Attempting to dispatch bundle 0x30106aabc4ec435e89b2493202bd324f on 1068269C-A4E6-400F-A427-D2251BC9F780
2020-06-24 23:18:16,632 Dispatching bundle 0x100d4c5bc6ae4a4cb839ce488a484122
2020-06-24 23:18:16,632 Attempting to dispatch bundle 0x100d4c5bc6ae4a4cb839ce488a484122 on 1068269C-A4E6-400F-A427-D2251BC9F780
2020-06-24 23:18:16,947 Dispatching bundle 0x1f67a2c27feb4594adefec144c1b690b
.....output continues for a long time......
```

Notice that it's trying to dispatch the bundle on the worker, which we've already exited. If you look at the log timestamps, it takes around ~0.3 seconds to process each bundle in the loop. 0.3 seconds per bundle * 5000 bundles = 1500 seconds = 25 minutes, where it'll just be stuck in this loop. While it does this, no dead workers are cleaned up, no staged bundles are set to running—to the end user, the BundleManager appears completely unresponsive.

**Comment by candicegjing** [comment] 2020-06-24 23:39
> Notice that it's trying to dispatch the bundle on the worker, which we've already exited. If you look at the log timestamps, it takes around ~0.3 seconds to process each bundle in the loop. 0.3 seconds per bundle * 5000 bundles = 1500 seconds = 25 minutes, where it'll just be stuck in this loop. While it does this, no dead workers are cleaned up, no staged bundles are set to running—to the end user, the BundleManager appears completely unresponsive.

`0.3` seconds per bundle seems to be very long. On dev environment, what I am seeing is `4.1464572611274775e-06` seconds per bundle. Did you test using codalab.stanford.edu right?

**Comment by nelson-liu** [comment] 2020-06-24 23:44
> 0.3 seconds per bundle seems to be very long. On dev environment, what I am seeing is 4.1464572611274775e-06 seconds per bundle. Did you test using codalab.stanford.edu right?

It's very long because it's failing—it's trying to run on a worker that doesn't exist. If you look at the function that starts the bundle ( https://github.com/codalab/codalab-worksheets/blob/master/codalab/server/bundle_manager.py#L544-L548 ; https://github.com/codalab/codalab-worksheets/blob/master/codalab/model/worker_model.py#L383-L385 ) , you'll see that it sleeps for 0.3 seconds when things fail. So, 0.3 s per loop is actually pretty much a lower bound?

> Did you test using codalab.stanford.edu right?

I observed this on codalab.stanford.edu first. The instructions above are tests I ran on my local macbook, since I didn't want to test on (stanford) prod :) The timings are similar, and the specs of my macbook are actually slightly better than codalab.stanford.edu, i think...

**Comment by candicegjing** [comment] 2020-06-25 23:12
> It's very long because it's failing—it's trying to run on a worker that doesn't exist. If you look at the function that starts the bundle ( https://github.com/codalab/codalab-worksheets/blob/master/codalab/server/bundle_manager.py#L544-L548 ; https://github.com/codalab/codalab-worksheets/blob/master/codalab/model/worker_model.py#L383-L385 ) , you'll see that it sleeps for 0.3 seconds when things fail. So, 0.3 s per loop is actually pretty much a lower bound?

I do see what you were seeing now. I am able to reproduce this locally and `0.3s` is a lower bound. Sometimes I saw `0.6s`. If a large number of bundles fail at sending json request to an offline worker, this is definitely a problem.

**Closed as completed** 2020-07-02 18:40 UTC
Labels: user-question
