### ISSUE TITLE
more options in New Run button

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1071] opened 2019-03-11 05:51 UTC
_From @percyliang on April 21, 2016 21:26_

Have an 'advanced' link that shows the following things:
- Allow users to specify the docker image (textbox with autocomplete).
- Allow people to specify the queue (e.g., jag).
- Allow people to specify a name.

Also allow people to paste in long commands.

_Copied from original issue: codalab/codalab-worksheets#152_

**Comment by w0nche0l** [comment] 2019-03-11 05:51
_From @maxwang7 on February 1, 2017 9:49_

This sounds cool! @percyliang Is this issue at design doc or implementation stage?

**Comment by bkgoksel** [comment] 2019-03-20 22:07
Duplicate of #1044 
Looks like we aspired to doing this 3 years ago too @percyliang @nikhilxb.

**Closed as completed by bkgoksel** 2019-03-20 22:07 UTC
