### ISSUE TITLE
[PROD ISSUE] ValueError: Header value must not contain control characters: 'inline; filename="input.json\r"'

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2671] opened 2020-07-30 02:47 UTC
```Error on request by public(None):

GET /bundles/0xacd024a7c19a4083989a7c1f81a9071b/contents/blob/input.json

Query params:

Form params:

JSON body:
<none>

Local variables:
value='inline; filename="input.json\r"'

Traceback (most recent call last):
File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 105, in wrapper
return callback(*args, **kwargs)
File "/usr/local/bin/bottle.py", line 1748, in wrapper
rv = callback(*a, **ka)
File "/opt/codalab-worksheets/codalab/server/json_api_plugin.py", line 18, in wrapper
result = callback(*args, **kwargs)
File "/opt/codalab-worksheets/codalab/server/authenticated_plugin.py", line 133, in wrapper
return callback(*args, **kwargs)
File "/opt/codalab-worksheets/codalab/rest/bundles.py", line 652, in _fetch_bundle_contents_blob
response.set_header('Content-Disposition', 'inline; filename="%s"' % filename)
File "/usr/local/bin/bottle.py", line 1553, in set_header
self._headers[_hkey(name)] = [_hval(value)]
File "/usr/local/bin/bottle.py", line 1416, in _hval
raise ValueError("Header value must not contain control characters: %r" % value)
ValueError: Header value must not contain control characters: 'inline; filename="input.json\r"'```

**Comment by epicfaace** [comment] 2020-07-30 12:57
I think we might need to strip filenames before uploading -- somehow they might be ending with an `\r`?

**Comment by yshen-google** [comment] 2020-08-29 05:36
Not sure how this bug can be reproduced. I tried the normal workflow `cl upload <filename>`, the possible faulty workflow `cl upload <filename>\r` as well as `cl upload <filename>/r`. The first one works seamlessly, and the latter 2 raise proper `UsageError` with non-existing file. Even though we cannot reproduce it in local environment, we could still rstrip the filename like `filename.rstrip()`. WDYT?

**Comment by percyliang** [comment] 2020-09-29 03:08
Can you programatically create a file with a "\r" in it and try uploading it?  You can try other weird characters too.  Would be nice to understand what's going on first.  But once we understand, then `rstrip()` sounds good.

**Comment by yshen-google** [comment] 2020-10-04 01:03
Tested it again in the following ways:
1. `touch input.json\r` and then `cl upload`, there is no problem and the filename is shown as `input.jsonr`.
2. Use Python file API to create file `input1.json\r` and the upload, no problem again and the filename is shown as `input1.json-`.
Also tested with some other special characters other than the one mentioned in the bug, it functions well. I am going to close this bug as WAI. Feel free to reopen it if a similar issue arises.

**Closed as completed by yshen-google** 2020-10-04 01:03 UTC
Labels: bug, backend, starter, p1
