### ISSUE TITLE
[USER ISSUE] Can't view contents of worksheet

### ISSUE THREAD

**Issue by ajoshi80** [codalab/codalab-worksheets#1580] opened 2019-10-30 22:10 UTC
**Describe the bug**
Attempting to open this worksheet on the website : 0xf38cc8163bc947848b3289ba6059f183

Seeing this error: Unexpected error while parsing line 2090

**Codalab Information**
- *Your username*:anirudhjoshi
- *UUID of worksheet where problem occurred*:0xf38cc8163bc947848b3289ba6059f183
- *UUID of problem bundle (please don't delete)*:0xf38cc8163bc947848b3289ba6059f183
- *Error message received from Codalab (if applicable)*:Unexpected error while parsing line 2090
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; Safari

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/47344101/67902860-62b77f80-fb27-11e9-8358-e4c5a4cdaf44.png">

**Additional context**

**Comment by yipenghe** [comment] 2019-11-03 19:56
Might be caused by some error in source, maybe click on Edit source to see if anything's weird on line 2090, maybe take out line 2090 and see if it goes through?

**Comment by Levilian** [comment] 2019-11-06 22:13
@ajoshi80 If possible, can you let us know what's on line 2090 so we can potentially reproduce the bug and fix it?

**Comment by percyliang** [comment] 2019-11-14 01:55
Closing for now, please re-open if you find another example.

**Closed as completed by percyliang** 2019-11-14 01:55 UTC
Labels: user-question
