### ISSUE TITLE
Upgrading doesn't work with cl-worker-public.sh

### ISSUE THREAD

**Issue by klopyrev** [codalab/codalab-worksheets#577] opened 2016-08-23 00:15 UTC
It tries to write to the directory where the public code is stored and then just gets stuck in a restart loop.

@percyliang

**Comment by percyliang** [comment] 2016-08-23 15:02
Just tried it with both 'main' and 'nlp' arguments.  This doesn't happen
for me, but yes, I've seen this kind of behavior independent of this script.

Seems like having the worker update the source when it's pointing into the
git repo can cause problems...

**Comment by klopyrev** [comment] 2016-08-23 15:25
Doesn't happen for you because you actually have write access to the
directory.

**Comment by percyliang** [comment] 2016-08-23 15:43
Which directory are you talking about?
Everything in /u/nlp/data/codalab/codalab-cli/worker is owned by the
codalab user.

**Comment by kashizui** [comment] 2016-09-27 05:57
What is the status of this issue?

**Comment by percyliang** [comment] 2016-09-27 06:03
Don't know.  It works for me, and I believe for Pranav as well.  Can you
try it and close it if it works for you?

**Comment by kashizui** [comment] 2016-09-27 21:39
@percyliang Will do.

I can't find the `cl-worker-public.sh` script -- what is it and where can I find it?

**Comment by percyliang** [comment] 2016-09-27 21:40
It's called cl-worker.sh

**Comment by kashizui** [comment] 2016-09-27 21:44
Is this in codalab-cli? Do you mean `worker.sh`?

**Comment by percyliang** [comment] 2016-09-27 21:46
No this is only on hte NLP machines /u/nlp/bin/cl-worker.sh

**Comment by kashizui** [comment] 2016-09-27 21:48
Ah thanks!

**Comment by kashizui** [comment] 2016-09-27 21:56
Works for me from the NLP CodaLab machine!

**Comment by klopyrev** [comment] 2016-09-28 00:27
That's because you guys have access to write to the CodaLab directory. It
doesn't work for anyone else.

**Comment by kashizui** [comment] 2016-09-28 00:31
What's the best way for me to reproduce this?

**Comment by kashizui** [comment] 2016-10-27 06:15
Finally understood the issue (I think).
Two (orthogonal) fixes:
- Don't support upgrading if user doesn't own the code directory. (Ignore upgrade messages from the server if the worker doesn't have the right permissions on the worker code directory, and perhaps print a warning to that effect instead of crashing and getting stuck in a restart loop.)
- Allow worker code directory to sit somewhere independently from the codalab-cli directory, so that users can keep their own upgradable copy.

**Comment by kashizui** [comment] 2017-01-12 22:58
Actually the second point is already true. Maybe we can just have the clworker.sh script make a copy of the worker code directory into the user's working directory, and start the worker process from there.

**Comment by kashizui** [comment] 2017-01-13 07:08
Tried it out: even with the right permissions, the current self-upgrade procedure actually doesn't work on AFS:
```
Traceback (most recent call last):
  File "/afs/cs.stanford.edu/u/codalab/codalab-worker-code/worker.py", line 245, in _upgrade
  File "/afs/cs.stanford.edu/u/codalab/codalab-worker-code/file_util.py", line 225, in remove_path
  File "/usr/lib64/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib64/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: '/afs/cs.stanford.edu/u/codalab/codalab-worker-code/.__afs0E65'
```
or on NFS:
```
Traceback (most recent call last):
  File "/juicier/scr129/scr/codalab/codalab-worker-nlp-code/worker.py", line 245, in _upgrade
  File "/juicier/scr129/scr/codalab/codalab-worker-nlp-code/file_util.py", line 225, in remove_path
  File "/usr/lib64/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib64/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: '/juicier/scr129/scr/codalab/codalab-worker-nlp-code/.nfs000000000bc001840000004e'
```

**Comment by percyliang** [comment] 2017-01-13 07:57
Can we run the worker from a local disk (/scr)?

**Comment by kashizui** [comment] 2017-01-14 06:34
When I tried it in `/scr` I got the second error that I pasted above (the first error was from trying it in the home directory). I'm still not sure how to sidestep this issue.

**Comment by percyliang** [comment] 2017-01-14 06:39
I guess /scr is still on NFS.  Try /tmp?

**Comment by kashizui** [comment] 2017-01-14 06:57
That works!
I've updated `/u/nlp/bin/cl-worker.sh` to use `/tmp` for the worker code.
What's the cleanup policy of `/tmp` on codalab.stanford.edu? Do we have to worry about that?

**Comment by percyliang** [comment] 2017-01-14 07:09
Probably we should cleanup after ourselves anyway (that's another issue).
Also, bundles are directly written into the bundle store, which means we
don't have to worry about /tmp filling up (but should double check).

**Comment by kashizui** [comment] 2017-01-14 07:51
I added a line to the script to remove the code directory from tmp when the worker terminates.

**Comment by kashizui** [comment] 2017-01-14 07:52
tmp looks fine!

**Comment by kashizui** [comment] 2017-01-14 07:52
Closing as complete now.

**Closed as completed by kashizui** 2017-01-14 07:52 UTC
