### ISSUE TITLE
rebuild default docker images

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#538] opened 2016-07-19 15:01 UTC
We've been using `codalab/ubuntu:1.9` for a while as the default, but need to associate this with an Dockerfile and automated build.

At this point, consider splitting this into multiple official containers - one with Java, etc., one for Python, etc.

Then we must make it easy for people to autocomplete the docker image, discover them, and select it when they run things.

We might consider making docker containers more of a first-class citizen in CodaLab, so you can see the list of docker containers that people have used.

**Comment by fabeschan** [comment] 2017-02-02 04:30
As an aside, how was the current codalab/ubuntu:1.9 built? It doesn't correspond to the Dockerfile in the repo and somehow pip install is broken in the image.

**Comment by percyliang** [comment] 2017-02-02 04:55
It was built ad-hocly unfortunately.  There is a github issue for
rebuilding it using a Dockerfile.

**Comment by bkgoksel** [comment] 2018-08-03 22:55
Duplicate of #925

**Closed as completed by bkgoksel** 2018-08-03 22:55 UTC
