### ISSUE TITLE
deleting bundle makes cursor disappear

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2363] opened 2020-06-07 05:40 UTC
To reproduce, create a new worksheet.  Add a markdown block.  Add a run bundle.  Then delete the bundle (using keyboard shortcuts).  Then the cursor disappears (should be on the markdown block).  When try to cursor around, get:
![Screenshot from 2020-06-06 22-39-46](https://user-images.githubusercontent.com/435384/83961304-a6edc980-a846-11ea-8b11-3521d159635e.png)

**Comment by yuqijin** [comment] 2021-01-12 09:28
The issue should be fixed by PR #2963. I cannot reproduce the issue anymore. @epicfaace  Could you reproduce the issue for now?

**Comment by epicfaace** [comment] 2021-01-22 21:40
I can no longer reproduce this issue, either.

**Closed as completed by epicfaace** 2021-01-22 21:40 UTC
Labels: bug, frontend, p1
