### ISSUE TITLE
Unable to signup using outlook emails

### ISSUE THREAD

**Issue by miaosenwang** [codalab/codalab-worksheets#352] opened 2017-09-10 23:55 UTC
When I try to sign up the service using my outlook.com email, it returns "Invalid Email address" error.

**Comment by maxwang7** [comment] 2017-10-04 08:10
@miaosenwang I tried with a outlook.com email address and didn't have a problem. Would you mind giving me your email address so I can try and reproduce the problem? Thanks!

**Comment by maxwang7** [comment] 2017-10-09 08:11
Hi @miaosenwang I wanted to follow up on my previous comment. I'm unable to reproduce this error so it would be great to learn more about your problem. I will close this problem unless we find a way to reproduce it.

**Closed** 2017-10-15 23:46 UTC
