### ISSUE TITLE
[USER ISSUE] competitiond.py script can erroneously report null scores

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#1319] opened 2019-08-12 07:48 UTC
**Describe the bug**
`scripts/competitiond.py` can non-deterministically give null entries for scores, instead of the actual scores.

**Codalab Information**
- *Your username*: robinjia
- *UUID of worksheet where problem occurred*: 0xbe5f6ba1dd1c47ab8fe68c9b885f3e22
- *UUID of problem bundle (please don't delete)*: N/A
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: At commit 0c4f360c3328180f7ae07cd73ecf30d90db3dc95 in git (I was originally on a very old commit when I found this bug. I updated and found the same problem still happens)
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

1. `cd` to `codalab-worksheets`
2. Download the attached `config.json` file (github made me save it as `.txt`)
[config.json.txt](https://github.com/codalab/codalab-worksheets/files/3491379/config.json.txt)
3. Run `python scripts/competitiond.py -v config.json results.json`
4. (Unclear if needed) wait a few minutes.
5. Run `python scripts/competitiond.py -v config.json results2.json`
6. `vimdiff results.json results2.json`. Observe that at different times, different entries are reported as having `null` scores.

**Expected behavior**
Only submissions that had some failures (or are still running) should have `null` scores. For this leaderboard at this particular time, that means only 3 submissions should have `null`.

**Additional context**
In downstream processing, I typically treat "null" as a sign that either the submission failed or it is still running, and we should ignore it. This is obviously bad if the submission actually worked.

I am now concerned that this has also affected the SQuAD leaderboard, though I have not verified this yet. There was one incident I recall when a group e-mailed me complaining that their submission had been removed from the SQuAD leaderboard. I reran the `competitiond.py` script and it reappeared.

**Comment by candicegjing** [comment] 2019-10-14 18:01
Discussed with @robinjia on 10/14/2019. We reran the script on both sides and still couldn't reproduce the error. We decided to temporarily close this ticket for now. If we see it in the future, we will reopen it and investigate it again.

**Closed as completed** 2019-10-15 18:22 UTC
Labels: user-question
