### ISSUE TITLE
Runs take longer on codalab than on corresponding machine

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#985] opened 2018-10-28 09:02 UTC
Reported by @thashim

Example run command:
```cl run datasets:0xd26e61 word_vectors:0xfee84c cond-editor-codalab:0x921a48 'export COPY_EDIT_DATA=$(pwd); cd cond-editor-codalab; python
train_seq2seq.py default.txt' --request-memory 5G --request-gpus 1 --request-docker-image kelvinguu/textmorph:1.2```

Should take 2 hours, takes ~6 hours on codalab.

**Comment by bkgoksel** [comment] 2019-03-20 21:40
Duplicate of #1045

**Closed as completed by bkgoksel** 2019-03-20 21:40 UTC
