### ISSUE TITLE
[New Frontend] Delete button is too dangerous

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1659] opened 2019-11-13 17:21 UTC
1. Does the delete button in the top right delete the worksheet? 
2. Redesign functionality? The delete button looks scary and maybe it shouldn't be so easy to do that.

**Comment by yipenghe** [comment] 2019-11-14 03:59
duplicate of #1619

**Closed as completed by yipenghe** 2019-11-14 03:59 UTC
Labels: frontend
