### ISSUE TITLE
upload doesn't work after edit source

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#50] opened 2015-12-30 04:30 UTC
To reproduce bug:

1. On a new worksheet, upload a bundle.
2. Click 'Edit source' and save it (press ctrl-enter).
3. Upload a new bundle.

3 doesn't work.  One needs to refresh the entire page after 2. for 3. to work.

**Comment by ChengshuLi** [comment] 2016-01-18 23:42
The problem is actually not 'upload doesn't work after edit source'. The problem is 'upload doesn't work if the user upload the same file consecutively.' 

Now fixed. Feel free to checkout the PR.

**Closed** 2016-01-19 18:26 UTC
Labels: bug, P1
