### ISSUE TITLE
[USER ISSUE] Worksheets disappeared from dashboard but disk quota is still occupied

### ISSUE THREAD

**Issue by Ajanulk** [codalab/codalab-worksheets#1989] opened 2020-02-12 02:33 UTC
**Describe the bug**
My two worksheets are suddenly invisible and inaccessible on the dashboard, but disk quota still exists and bundles in the two worksheets are accessible and floating. These bundles' host worksheets become None. 

**Codalab Information**
- *Your username*:lrh001
- *UUID of worksheet where problem occurred*: 0xdcc8c840b5cd4243b6f90ade484aa9ae; The other is not recorded. 
- *Error message received from Codalab (if applicable)*:

b"No worksheet found with name 'wsl-hotpotqa'/'hotpotqa-test'"

 - *OS (if on CLI)*: Ubuntu 16.04
 - *Codalab CLI Version (if on CLI)*: 0.5.8

**Expected behavior**
Get back the worksheets.

**Screenshots**
![image](https://user-images.githubusercontent.com/48608537/74297356-94282400-4d81-11ea-9b20-4ba532b1f9a2.png)

**Comment by candicegjing** [comment] 2020-02-20 00:41
@Ajanulk I did checks on our side. It seems that your worksheet doesn't exist in our system. That's why you are seeing "Not found:..." error. Do you happen to remember anything that you think could contribute to this?

**Comment by Ajanulk** [comment] 2020-02-21 01:15
@candicegjing Thanks for reply. The first time this happened was when I was uploading a bundle. The second time it happened suddenly when I refreshed the frontend after I finished uploading and running.

If any, during the first upload, I used the `cl-worker --server` command. I did nothing at the second time.

**Comment by candicegjing** [comment] 2020-03-02 23:18
@Ajanulk Do you remember how large your bundle is when you were trying to upload the bundle for the first time? 
Also what's the version of `codalab` package in your local machine where you were trying to use `cl-worker`?

**Comment by Ajanulk** [comment] 2020-03-06 01:01
> @Ajanulk Do you remember how large your bundle is when you were trying to upload the bundle for the first time?
> Also what's the version of `codalab` package in your local machine where you were trying to use `cl-worker`?

@candicegjing Many thanks for your attention. 
1. About 2G
2. version 0.5.8

**Comment by candicegjing** [comment] 2020-03-07 18:27
@Ajanulk I recently tried to upload a file with a size similar to what you had, haven't found the worksheet disappeared issue yet. For the `codalab` package version, could you upgrade to the latest version `0.5.9` to try it out and see if the problem still persisits?

**Comment by candicegjing** [comment] 2020-03-19 17:26
Since we can't reproduce this issue, we close this ticket for now and will reopen if we see it happens again in the future.

**Closed as completed by candicegjing** 2020-03-19 17:26 UTC
Labels: user-question
