### ISSUE TITLE
can't sign up for account

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1201] opened 2019-06-11 16:15 UTC
When try to create an account, I filled out all the fields, but it asks me 'Please fill out this field' for the 'First Name', which clearly is filled in.

**Comment by bkgoksel** [comment] 2019-06-11 18:31
Can't reproduce this. This works for me on Firefox on Windows.

**Comment by percyliang** [comment] 2019-06-11 18:52
Ok, signing up seems to work, but the email for verifying the account redirects to a
https://127.0.0.1/rest/account/verify/.. URL, which doesn't work.

**Comment by XingLuxi** [comment] 2019-06-27 02:33
When login from the CLI via command `cl work`, return an error  `codalab.client.json_api_client.JsonApiException: Unable to fetch worksheets: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>`.
How can I fix it?

**Comment by bkgoksel** [comment] 2019-06-27 04:17
Hi XingLuxi,
This is an issue with your Python environment (and not the codalab package). What's happening is that Python is unable verify the certificate chain of our server. This is either because you don't have the correct root certificates installed in your system/python environment or some component of your TLS stack is out of date (like openssl). 

Please make sure your Python SSL components (certifi package for python/ openssl version / ca-certificates etc) are all up to date and not corrupted, and try again.

Good luck!

**Comment by XingLuxi** [comment] 2019-06-27 06:00
Thanks, @bkgoksel 
I changed the Python version from 2.7.16 to 2.7.10 in the virtual environment and it fixed.

Thanks Again

**Comment by epicfaace** [comment] 2019-08-25 21:43
@percyliang I can't reproduce this on `frontend`, so I'm just closing this -- but if you can reproduce it, feel free to reopen.

**Closed as completed by epicfaace** 2019-08-25 21:43 UTC
Labels: bug, frontend
