### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#539] opened 2016-07-23 14:20 UTC
After installation, each type one types 'cl ...' into the web terminal, the rest server prompts for a username / password.

**Comment by kashizui** [comment] 2016-08-06 07:24
@percyliang I'm not sure I can reproduce this, I'm only getting asked for user/pass on the first command. On Ubuntu 16.04.1:
```
ubuntu@ubuntu16:~/codalab-cli$ cl work localhost::
Requesting access at http://localhost:2800
Username: codalab
Password:
Switched to worksheet http://localhost:2800::home-codalab(0x2f128e1182bc425da6dddc4888c5819a).
ubuntu@ubuntu16:~/codalab-cli$ cl ls
### Worksheet: http://localhost:2800::home-codalab(0x2f128e1182bc425da6dddc4888c5819a)
### Title: <none>
### Tags:
### Owner: codalab(0)
### Permissions: public(0x682b58):read
ubuntu@ubuntu16:~/codalab-cli$ cl ls
### Worksheet: http://localhost:2800::home-codalab(0x2f128e1182bc425da6dddc4888c5819a)
### Title: <none>
### Tags:
### Owner: codalab(0)
### Permissions: public(0x682b58):read
ubuntu@ubuntu16:~/codalab-cli$ cl work localhost::
Switched to worksheet http://localhost:2800::home-codalab(0x2f128e1182bc425da6dddc4888c5819a).
ubuntu@ubuntu16:~/codalab-cli$ cl ls
### Worksheet: http://localhost:2800::home-codalab(0x2f128e1182bc425da6dddc4888c5819a)
### Title: <none>
### Tags:
### Owner: codalab(0)
### Permissions: public(0x682b58):read
ubuntu@ubuntu16:~/codalab-cli$
```

**Comment by kashizui** [comment] 2016-08-06 09:15
@percyliang I'm not able to reproduce this, I'm only getting asked for user/pass twice on Ubuntu 16.04.1 amd64, which is expected on the `master` branch. This issue is fixed on `develop` but hasn't been merged/deployed yet.

**Comment by percyliang** [comment] 2016-08-06 19:38
The problem is not with typing cl into the shell.  The problem is when you
try commands into the web terminal.  To be more specific:
I type 'cl run date' into the web terminal and then the rest server asks me
for a user name/password.  Then the command gets executed.  If I do this
again, same thing.

I'm seeing this on both develop and master.

**Comment by kashizui** [comment] 2016-08-07 03:02
This appears to be the result of a hotfix I added in response to a problem affecting users connecting to the Stanford instance over SSH tunnel. This has been fixed temporarily on worksheets.codalab.org but opened a PR #559 for a better fix.

**Closed as completed** 2016-08-17 04:47 UTC
Labels: bug
