### ISSUE TITLE
progress bar for uploading bundles

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#20] opened 2015-12-27 10:10 UTC
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Thursday Oct 15, 2015 at 03:54 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1338_

----

When do
cl upload
in the web terminal, shows upload dialog.  For large files, it would be good to show partial progress rather than hanging for a while.

**Comment by kashizui** [comment] 2016-05-19 04:45
Duplicate of #40

**Closed by kashizui** 2016-05-19 04:45 UTC
Labels: P2
