### ISSUE TITLE
404 page should not show HTML

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3226] opened 2021-01-27 15:23 UTC
The 404 page ("worksheet not found") should not show HTML. Right now, it shows HTML, which doesn't look good.

![image](https://user-images.githubusercontent.com/1689183/106012728-b47fea00-6089-11eb-8f2c-aac5640d0638.png)

**Comment by yuqijin** [comment] 2021-02-07 10:20
Hi @epicfaace , which browser are you using? Could you provide more context on how to reproduce the error page? I tried with both Firefox and Chrome but still could not see your page.

<img width="664" alt="Screen Shot 2021-02-07 at 2 17 56 AM" src="https://user-images.githubusercontent.com/34461466/107143638-f7905780-68ea-11eb-9a04-ac05fc13ff5b.png">
<img width="833" alt="Screen Shot 2021-02-07 at 2 18 05 AM" src="https://user-images.githubusercontent.com/34461466/107143639-f8c18480-68ea-11eb-87e4-7cebedfb7dd7.png">
<img width="1327" alt="Screen Shot 2021-02-07 at 2 18 15 AM" src="https://user-images.githubusercontent.com/34461466/107143641-f9f2b180-68ea-11eb-985e-ed3b0213239a.png">

**Comment by epicfaace** [comment] 2021-02-07 22:27
Hmm, I don't recall how I reproduced this, and I can't seem to reproduce it now. If you can't reproduce this anymore, then we can just close it.

**Comment by yuqijin** [comment] 2021-02-08 07:46
Close the issue for now since it cannot be reproduced anymore.

**Comment by epicfaace** [comment] 2021-02-09 23:02
Wait, I was able to reproduce it. It looks like it's happening when the `http://localhost/rest/user?_=1612911590913` endpoint gives a 404 (so you may need to simulate that to reproduce it). Essentially, in my case, it happens when the REST server is down when running codalab locally.

![image](https://user-images.githubusercontent.com/1689183/107439898-cab58d80-6b00-11eb-8db8-cc0dd5077cfc.png)

**Closed as completed** 2021-02-12 11:33 UTC
Labels: frontend, p1
