### ISSUE TITLE
Truncation upon file upload

### ISSUE THREAD

**Issue by lynn-he** [codalab/codalab-worksheets#3513] opened 2021-05-16 18:47 UTC
Some JSON files are truncated upon manual upload. If you click into the UUID of the problem bundle listed below and scroll to the bottom of the uploaded file, you will see the JSON is truncated, while the original local file is complete. 

[dev_x.json.zip](https://github.com/codalab/codalab-worksheets/files/6502916/dev_x.json.zip)

 

**Codalab Information**
- *Your username*: DeepLearning.AI
- *UUID of worksheet where problem occurred*: 0x54ed2618d75944f789477fc15ea660c8
- *UUID of problem bundle (please don't delete)*: 0xaddb3ca4ff4649f28d44c68a6f4e086a
- *Error message received from Codalab (if applicable)*: N/A
 - *OS (if on CLI)*: MacOS Catalina Version 10.15.17
 - *Codalab CLI Version (if on CLI)*: 0.5.47
 - *Browser (if on Web)*; Chrome

**Expected behavior**
All manually uploaded files to appear as bundles without a cutoff.

**Additional context**
see truncation: https://worksheets.codalab.org/rest/bundles/0xaddb3ca4ff4649f28d44c68a6f4e086a/contents/blob/

**Comment by epicfaace** [comment] 2021-09-15 02:09
@lynn-he how often did this happen for you? Do you still see it happening now?

**Comment by percyliang** [comment] 2021-09-15 06:25
This is expected behavior since we need to cap the size of files that are loaded into memory.  The recommendation is to output only the statistics that you need into your JSON file.  We could make this clearer in the documentation though.

**Comment by lynn-he** [comment] 2021-09-17 19:19
thanks for following up. @epicfaace this was not happening consistently, just noticed it a couple times at the beginning of setting up the competition and while we were testing file uploading. @percyliang thanks for making me aware of this, we will keep that in mind for the future.

**Comment by epicfaace** [comment] 2021-09-18 02:33
Okay, closing this issue for now, then.

**Closed as completed by epicfaace** 2021-09-18 02:33 UTC
Labels: user-question, frontend, p2
