### ISSUE TITLE
codalab cp command Permission denied

### ISSUE THREAD

**Issue by JiexingQi** [codalab/codalab-worksheets#4053] opened 2022-03-26 14:37 UTC
**Describe the bug**
I use cp command on shell file, but codalab error shows ：Permission denied

**Codalab Information**
- *Your username*: jxqi
- *UUID of worksheet where problem occurred*: 
- *UUID of problem bundle (please don't delete)*:0x034fda3f20a444b99a5da6474c4c565e
- *Error message received from Codalab (if applicable)*:
run_prediction.sh: line 4: sudo: command not found
cp: cannot create directory '/app/gen-cpp2/gen-cpp2': Permission denied
cp: cannot create directory '/app/gen-py3/gen-py3': Permission denied
[FAILURE:picard.thrift] Couldn't open "./gen-cpp2/picard_data.h" for writing.
[FAILURE:picard.thrift] Couldn't open "./gen-py3/picard/types.pyx" for writing.
error: could not delete 'picard/libpicard.cpython-37m-x86_64-linux-gnu.so': Permission denied
cp: cannot create regular file '/app/cabal.project': Permission denied
cp: cannot create regular file '/app/fb-util-cabal.patch': Permission denied
cp: cannot create regular file '/app/gen-hs/picard-gen-hs.cabal': Permission denied
cp: cannot create regular file '/app/picard/src/Language/SQL/SpiderSQL/Lexer.hs': Permission denied
cp: cannot create regular file '/app/picard/src/Language/SQL/SpiderSQL/Prelude.hs': Permission denied
cp: cannot create regular file '/app/picard/src/Language/SQL/SpiderSQL/Syntax.hs': Permission denied
cp: cannot create regular file '/app/picard/src/Language/SQL/SpiderSQL/Parse.hs': Permission denied
cp: cannot create regular file '/app/picard/src/Language/SQL/SpiderSQL.hs': Permission denied
cp: cannot create regular file '/app/picard/src/Control/Monad/Yoctoparsec/Class.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Spec.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/PhoneMarket.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/ConcertSinger.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/PokerPlayer.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Singer.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Inn1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Car1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/MuseumVisit.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/ProductCatalog.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Academic.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/CreDocTemplateMgt.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Orchestra.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Wta1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/StudentTranscriptsTracking.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Flight1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Geo.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Chinook1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/AssetsMaintenance.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/TestItem.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Pets1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/DepartmentManagement.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/StormRecord.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Bike1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/DogKennels.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Scholar.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/MatchSeason.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/doctests.hs': Permission denied
cp: cannot create regular file '/app/picard/picard.cabal': Permission denied
cp: cannot create regular file '/app/picard/Setup.hs': Permission denied
cp: cannot create regular file '/app/picard/exe/Main.hs': Permission denied
/app/dist-newstyle: createDirectory: permission denied (Permission denied)
thrift-compiler: ./gen-hs/Picard/Types.hs: openFile: permission denied (Permission denied)
patch: **** Can't create temporary file common/util/fb-util.cabal.o9rXZ5N : Permission denied
[FAILURE:if/RpcOptions.thrift] Couldn't open "../cpp-channel/if/gen-cpp2/RpcOptions_data.h" for writing.
make: *** [thrift-cpp] Error 1

 - *OS (if on CLI)*:linux
 - *Codalab CLI Version (if on CLI)*: 1.4.6
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Go to '...' https://worksheets.codalab.org/bundles/0x034fda3f20a444b99a5da6474c4c565e
2. See error

**Expected behavior**
I use cp command on shell file,
some file content is as follows :
```
#!/bin/bash

pushd text-to-sql
sudo cp picard.thrift /app/
cp -r gen-cpp2 /app/gen-cpp2/
cp -r gen-py3 /app/gen-py3/
popd

pushd /app
thrift1 --gen mstch_cpp2 picard.thrift
thrift1 --gen mstch_py3 picard.thrift
pushd gen-py3
python setup.py build_ext --inplace
popd
popd

export PYTHONPATH=$PYTHONPATH:/app/gen-py3
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/app/gen-py3/picard

pushd text-to-sql
cp cabal.project fb-util-cabal.patch /app/
cp -r gen-hs /app/
cp -r picard /app/
popd
……
```

 however, it give me some error info. such as 
```
run_prediction.sh: line 4: sudo: command not found
cp: cannot create directory '/app/gen-cpp2/gen-cpp2': Permission denied
cp: cannot create directory '/app/gen-py3/gen-py3': Permission denied
[FAILURE:picard.thrift] Couldn't open "./gen-cpp2/picard_data.h" for writing.
[FAILURE:picard.thrift] Couldn't open "./gen-py3/picard/types.pyx" for writing.
error: could not delete 'picard/libpicard.cpython-37m-x86_64-linux-gnu.so': Permission denied
cp: cannot create regular file '/app/cabal.project': Permission denied
cp: cannot create regular file '/app/fb-util-cabal.patch': Permission denied
cp: cannot create regular file '/app/gen-hs/picard-gen-hs.cabal': Permission denied
cp: cannot create regular file '/app/picard/src/Language/SQL/SpiderSQL/Lexer.hs': Permission denied
cp: cannot create regular file '/app/picard/src/Language/SQL/SpiderSQL/Prelude.hs': Permission denied
cp: cannot create regular file '/app/picard/src/Language/SQL/SpiderSQL/Syntax.hs': Permission denied
cp: cannot create regular file '/app/picard/src/Language/SQL/SpiderSQL/Parse.hs': Permission denied
cp: cannot create regular file '/app/picard/src/Language/SQL/SpiderSQL.hs': Permission denied
cp: cannot create regular file '/app/picard/src/Control/Monad/Yoctoparsec/Class.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Spec.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/PhoneMarket.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/ConcertSinger.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/PokerPlayer.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Singer.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Inn1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Car1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/MuseumVisit.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/ProductCatalog.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Academic.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/CreDocTemplateMgt.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Orchestra.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Wta1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/StudentTranscriptsTracking.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Flight1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Geo.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Chinook1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/AssetsMaintenance.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/TestItem.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Pets1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/DepartmentManagement.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/StormRecord.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Bike1.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/DogKennels.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/Scholar.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/Language/SQL/SpiderSQL/MatchSeason.hs': Permission denied
cp: cannot create regular file '/app/picard/tests/doctests.hs': Permission denied
cp: cannot create regular file '/app/picard/picard.cabal': Permission denied
cp: cannot create regular file '/app/picard/Setup.hs': Permission denied
cp: cannot create regular file '/app/picard/exe/Main.hs': Permission denied
/app/dist-newstyle: createDirectory: permission denied (Permission denied)
thrift-compiler: ./gen-hs/Picard/Types.hs: openFile: permission denied (Permission denied)
patch: **** Can't create temporary file common/util/fb-util.cabal.o9rXZ5N : Permission denied
[FAILURE:if/RpcOptions.thrift] Couldn't open "../cpp-channel/if/gen-cpp2/RpcOptions_data.h" for writing.
make: *** [thrift-cpp] Error 1

```

**Screenshots**
![image](https://user-images.githubusercontent.com/43906450/160244311-8bbb72a7-b743-4d33-93d4-df0be5cfb1f7.png)

**Additional context**

**Comment by epicfaace** [comment] 2022-03-27 02:11
I think this is a duplicate of https://github.com/codalab/codalab-worksheets/issues/4054, is that right?

**Comment by JiexingQi** [comment] 2022-03-27 02:14
@epicfaace Hi, Thank you for your reply, It's the same problem to some extent, but the difference is that one is using the official codalab Docker image and this https://github.com/codalab/codalab-worksheets/issues/4054 is using someone else's custom image.

**Comment by epicfaace** [comment] 2022-03-28 13:39
OK, closing this as a duplicate of https://github.com/codalab/codalab-worksheets/issues/4054 then.

**Closed as completed by epicfaace** 2022-03-28 13:39 UTC
Labels: user-question
