### ISSUE TITLE
REST API for loading worksheet is slow

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1083] opened 2019-03-11 05:55 UTC
_From @ppasupat on April 13, 2016 21:15_

It seems that the API for loading a worksheet (`/rest/api/worksheets/<uuid>`) is transferring a lot of data. It turns out that the response JSON contains the list of all files in all bundles even though they are not needed for displaying the worksheet. The transfer is also not compressed I think.

On the worksheet page, selecting a bundle issues another API request which loads the list of files in the selected bundle, so I'm not sure why the worksheet API needs to return the file lists.

Example:
https://worksheets.codalab.org/worksheets/0x03d1850e5dce4578948a38bcf760acab/

_Copied from original issue: codalab/codalab-worksheets#147_

**Comment by w0nche0l** [comment] 2019-03-11 05:55
_From @ppasupat on April 13, 2016 21:20_

On a related note, when the worksheet page is loading, it also seems to issue a bundle read API request (`/rest/api/bundles/content/<uuid>`) for **each** bundle in addition to the worksheet read API. I'm not sure if this is redundant.

**Comment by ppasupat** [comment] 2019-03-12 00:40
I just checked the loaded JSONs and the issue no longer applies. Feel free to close the issue.

**Comment by bkgoksel** [comment] 2019-03-20 21:25
We do have a slow loading issue for large worksheets. Let's keep this open until we're sure it's fixed

**Comment by bkgoksel** [comment] 2019-03-20 21:57
Duplicate of #1055

**Closed as completed by bkgoksel** 2019-03-20 21:57 UTC
Labels: bug, backend
