### ISSUE TITLE
Copy doesn't work on web cli

### ISSUE THREAD

**Issue by rajpurkar** [codalab/codalab-worksheets#340] opened 2017-06-24 07:26 UTC
The shortcut command + c, command + v does not have intended copying behavior! It copies extra chunks of commands.

On mac OS sierra, chrome v58

**Comment by maxwang7** [comment] 2017-10-15 23:11
@rajpurkar I'm not able to reproduce, I'm on OS X Yosemite with Chrome v59. Could you send me a video of this being reproduced or could you let me know some times you're available and I can drop by to debug?

**Comment by maxwang7** [comment] 2017-10-21 04:25
@rajpurkar following up on this!

**Comment by maxwang7** [comment] 2017-10-22 21:34
Closing for now, but let me know if you'd like me to come take a look at it sometime and I can reopen the issue then!

**Closed by maxwang7** 2017-10-22 21:34 UTC
Labels: bug
