### ISSUE TITLE
the state is always uploading after choose a big file to upload

### ISSUE THREAD

**Issue by SayHelloToProgrammerWorld** [codalab/codalab-worksheets#1817] opened 2019-12-04 08:32 UTC

**Comment by yipenghe** [comment] 2019-12-04 08:37
Hi, upload takes time to happen, for some reason, for big files the progress icon doesn't show up. Alternatively you can monitor the upload progress by checking the bundle detail and see the file size changing, currently the detail doesn't auto update for uploading bundles, so you may need to open-close-open to see the size change

**Comment by SayHelloToProgrammerWorld** [comment] 2019-12-04 08:45
> Hi, upload takes time to happen, for some reason, for big files the progress icon doesn't show up. Alternatively you can monitor the upload progress by checking the bundle detail and see the file size changing, currently the detail doesn't auto update for uploading bundles, so you may need to open-close-open to see the size change

thank you for your advice@yipenghe. following your suggestion, I search more details of the uploading bundles, but there is no information about datasize

**Comment by yipenghe** [comment] 2019-12-04 08:47
> > Hi, upload takes time to happen, for some reason, for big files the progress icon doesn't show up. Alternatively you can monitor the upload progress by checking the bundle detail and see the file size changing, currently the detail doesn't auto update for uploading bundles, so you may need to open-close-open to see the size change
> 
> thank you for your advice@yipenghe. following your suggestion, I search more details of the uploading bundles, but there is no information about datasize

Hmmm, that's weird, so nothing shows up in the files section of the bundle details?

**Comment by SayHelloToProgrammerWorld** [comment] 2019-12-04 08:50
> Hi, upload takes time to happen, for some reason, for big files the progress icon doesn't show up. Alternatively you can monitor the upload progress by checking the bundle detail and see the file size changing, currently the detail doesn't auto update for uploading bundles, so you may need to open-close-open to see the size change
> 
> thank you for your advice@yipenghe. following your suggestion, I search more details of the uploading bundles, but there is no information about datasize
> 
> Hmmm, that's weird, so nothing shows up in the files section of the bundle details?

yep, the files section is blank

**Comment by yipenghe** [comment] 2019-12-04 08:52
> > Hi, upload takes time to happen, for some reason, for big files the progress icon doesn't show up. Alternatively you can monitor the upload progress by checking the bundle detail and see the file size changing, currently the detail doesn't auto update for uploading bundles, so you may need to open-close-open to see the size change
> > thank you for your advice@yipenghe. following your suggestion, I search more details of the uploading bundles, but there is no information about datasize
> > Hmmm, that's weird, so nothing shows up in the files section of the bundle details?
> 
> yep, the files section is blank

Do you mind sharing the uuid of the uploading bundle?

**Comment by SayHelloToProgrammerWorld** [comment] 2019-12-04 09:04
one of my uploading files uuid is 0x7035fe5ad5064b909a907c30d7db698c , thank you

**Comment by yipenghe** [comment] 2019-12-04 09:09
> 0x7035fe5ad5064b909a907c30d7db698c

I see, I think the bundle is uploading, the method I just described probably only works for zipped directory bundles, I will mark this down and try to add indication for uploading bundle about size. Not sure how long it might take (I uploaded a 466m a while ago and it took a while to finish uploading)

**Comment by SayHelloToProgrammerWorld** [comment] 2019-12-04 09:22
hello ,there is another question, how to recover the floating bundles

**Comment by yipenghe** [comment] 2019-12-04 09:25
> hello ,there is another question, how to recover the floating bundles

Go to dashboard to check your floating bundles, get the uuid. Go back to your worksheet, click edit source on top right, type []{uuid} inside that worksheet and save, you should see it in your worksheet. Planning to make this process less troublesome

**Comment by SayHelloToProgrammerWorld** [comment] 2019-12-04 09:59
thank you for your help

**Comment by SayHelloToProgrammerWorld** [comment] 2019-12-04 14:12
@yipenghe Hi, it takes so long to upload the file which exceeds1.3G , comparing to the time that it took to upload another 800M file (only a few minutes) . I wonder if there are any restrict on file size .

**Comment by SayHelloToProgrammerWorld** [comment] 2019-12-04 14:56
here is another question, the uploaded file(uuid 0x5ea34b015fcb4d10987e9bbc424fd9e9)  is not matched with its original size (its data size is only 22.8M while original size is 849M)

**Comment by SayHelloToProgrammerWorld** [comment] 2019-12-05 14:55
hi@yipenghe , progress icon shows up when uploading files that not exceed 1G, but the icon doesn't appear when uploading file bigger than 1G. I wonder if there are any restrict on file datasize.  hope to receive your reply!

**Comment by hello-deh** [comment] 2019-12-10 03:40
when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?

**Comment by yipenghe** [comment] 2019-12-10 04:02
> hi@yipenghe , progress icon shows up when uploading files that not exceed 1G, but the icon doesn't appear when uploading file bigger than 1G. I wonder if there are any restrict on file datasize. hope to receive your reply!

So sorry, it's final season and I didn't check emails regularly. I don't think we imposed a restriction but I will double check with the team

**Comment by yipenghe** [comment] 2019-12-10 04:03
> @yipenghe Hi, it takes so long to upload the file which exceeds1.3G , comparing to the time that it took to upload another 800M file (only a few minutes) . I wonder if there are any restrict on file size .

Thanks for sharing the observation

**Comment by yipenghe** [comment] 2019-12-10 04:06
> when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?

There might be some problem uploading large files, I will get back to you after checking with the team, sorry for the inconvenience

**Comment by SayHelloToProgrammerWorld** [comment] 2019-12-10 04:45
> when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?
> 
> There might be some problem uploading large files, I will get back to you after checking with the team, sorry for the inconvenience

@yipenghe ,thank you for your reply , I  have uploaded files through CLI last week, it proved to be more useful . I have another question , can you suggest a good way to clear memory? I have deleted my worksheet, but there are  a lot bundles in my recent bundles list

**Comment by yipenghe** [comment] 2019-12-10 04:52
> > when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?
> > There might be some problem uploading large files, I will get back to you after checking with the team, sorry for the inconvenience
> 
> @yipenghe ,thank you for your reply , I have uploaded files through CLI last week, it proved to be more useful . I have another question , can you suggest a good way to clear memory? I have deleted my worksheet, but there are a lot bundles in my recent bundles list

Great to know CLI worked, I think it might be related to how frontend handles file selection, I will test more after my finals.

For bulk deleting bundles, currently you would need to be on a worksheet that you have edit permission, I'm still thinking of a better logic to control this.
For now, I think the easiest way to remove a lot of bundles at once would be to:
1. create a new worksheet
2. copy the source on your dashboard (click 'view source' on top right) and paste in the new worksheet you just created (click edit source, paste and then save), you should now see checkboxes next to the bundle rows since you have edit permission on the newly created worksheet
3. bulk select all the bundles you want to delete, and click 'delete' on top left corner

**Comment by SayHelloToProgrammerWorld** [comment] 2019-12-10 05:01
thank you! it's a good method !

**Comment by SayHelloToProgrammerWorld** [comment] 2019-12-10 05:01
> when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?
> There might be some problem uploading large files, I will get back to you after checking with the team, sorry for the inconvenience
> 
> @yipenghe ,thank you for your reply , I have uploaded files through CLI last week, it proved to be more useful . I have another question , can you suggest a good way to clear memory? I have deleted my worksheet, but there are a lot bundles in my recent bundles list
> 
> Great to know CLI worked, I think it might be related to how frontend handles file selection, I will test more after my finals.
> For bulk deleting bundles, currently you would need to be on a worksheet that you have edit permission, I'm still thinking of a better logic to control this.
> For now, I think the easiest way to remove a lot of bundles at once would be to:
> 
> create a new worksheet
> copy the source on your dashboard (click 'view source' on top right) and paste in the new worksheet you just created (click edit source, paste and then save), you should now see checkboxes next to the bundle rows since you have edit permission on the newly created worksheet
> bulk select all the bundles you want to delete, and click 'delete' on top left corner

thank you! It's a good method!

**Comment by yipenghe** [comment] 2019-12-10 05:15
> when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?

Can you try using the CLI upload command for large files? It seems to be more stable

**Comment by hello-deh** [comment] 2019-12-10 06:16
> when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?
> 
> Can you try using the CLI upload command for large files? It seems to be more stable

when using cl upload <path>, It is unclear how to write "path". For example, my local file is D:\work\squad\model.zip,

**Comment by hello-deh** [comment] 2019-12-10 07:53
> when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?
> There might be some problem uploading large files, I will get back to you after checking with the team, sorry for the inconvenience
> 
> @yipenghe ,thank you for your reply , I  have uploaded files through CLI last week, it proved to be more useful . I have another question , can you suggest a good way to clear memory? I have deleted my worksheet, but there are  a lot bundles in my recent bundles list

I'm also trying CLI: cl upload <path>, I'm glad to know how to write "path" if my local file is D:\work\squad\model.zip (windows10 system) ?

**Comment by teetone** [comment] 2019-12-10 08:30
@hello-deh Can you comment on which browser and version you were using to perform the upload? Also, how large were the files?

**Comment by hello-deh** [comment] 2019-12-10 09:30
> @hello-deh Can you comment on which browser and version you were using to perform the upload? Also, how large were the files?

Microsoft Edge 44.17763.1.0， the size of model file to upload is about 3G

**Comment by hello-deh** [comment] 2019-12-11 06:17
> when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?
> There might be some problem uploading large files, I will get back to you after checking with the team, sorry for the inconvenience
> 
> @yipenghe ,thank you for your reply , I  have uploaded files through CLI last week, it proved to be more useful . I have another question , can you suggest a good way to clear memory? I have deleted my worksheet, but there are  a lot bundles in my recent bundles list

hello, Could you tell me how to use CLI: cl upload path, how to write "path" correctly? (suppose the local file is D:\work\squad\model_save.zip, windows 10 system, browser: Microsoft Edge 44.17763.1.0)

**Comment by yipenghe** [comment] 2019-12-11 23:30
> > when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?
> > There might be some problem uploading large files, I will get back to you after checking with the team, sorry for the inconvenience
> > @yipenghe ,thank you for your reply , I  have uploaded files through CLI last week, it proved to be more useful . I have another question , can you suggest a good way to clear memory? I have deleted my worksheet, but there are  a lot bundles in my recent bundles list
> 
> hello, Could you tell me how to use CLI: cl upload path, how to write "path" correctly? (suppose the local file is D:\work\squad\model_save.zip, windows 10 system, browser: Microsoft Edge 44.17763.1.0)

Hi, sorry for the late reply. Just asked another team member, the upload command doesn't work on Windows. Currently it seems no way to upload large files with Windows, which we are sorry about. We are working to see how to fix this problem. Can you find someone with Mac/linux to help you upload the bundle?

**Comment by hello-deh** [comment] 2019-12-12 01:31
> when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?
> There might be some problem uploading large files, I will get back to you after checking with the team, sorry for the inconvenience
> @yipenghe ,thank you for your reply , I  have uploaded files through CLI last week, it proved to be more useful . I have another question , can you suggest a good way to clear memory? I have deleted my worksheet, but there are  a lot bundles in my recent bundles list
> 
> hello, Could you tell me how to use CLI: cl upload path, how to write "path" correctly? (suppose the local file is D:\work\squad\model_save.zip, windows 10 system, browser: Microsoft Edge 44.17763.1.0)
> 
> Hi, sorry for the late reply. Just asked another team member, the upload command doesn't work on Windows. Currently it seems no way to upload large files with Windows, which we are sorry about. We are working to see how to fix this problem. Can you find someone with Mac/linux to help you upload the bundle?

I has two systems on my computer, ubuntu is accessable. So how to upload large file using "cl upload path" command on ubuntu?

**Comment by yipenghe** [comment] 2019-12-12 01:36
> > when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?
> > There might be some problem uploading large files, I will get back to you after checking with the team, sorry for the inconvenience
> > @yipenghe ,thank you for your reply , I  have uploaded files through CLI last week, it proved to be more useful . I have another question , can you suggest a good way to clear memory? I have deleted my worksheet, but there are  a lot bundles in my recent bundles list
> > hello, Could you tell me how to use CLI: cl upload path, how to write "path" correctly? (suppose the local file is D:\work\squad\model_save.zip, windows 10 system, browser: Microsoft Edge 44.17763.1.0)
> > Hi, sorry for the late reply. Just asked another team member, the upload command doesn't work on Windows. Currently it seems no way to upload large files with Windows, which we are sorry about. We are working to see how to fix this problem. Can you find someone with Mac/linux to help you upload the bundle?
> 
> I has two systems on my computer, ubuntu is accessable. So how to upload large file using "cl upload path" command on ubuntu?

if it's home/file.zip, then setting path as `~/file.zip` should work

**Comment by hello-deh** [comment] 2019-12-12 01:50
> when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?
> There might be some problem uploading large files, I will get back to you after checking with the team, sorry for the inconvenience
> @yipenghe ,thank you for your reply , I  have uploaded files through CLI last week, it proved to be more useful . I have another question , can you suggest a good way to clear memory? I have deleted my worksheet, but there are  a lot bundles in my recent bundles list
> hello, Could you tell me how to use CLI: cl upload path, how to write "path" correctly? (suppose the local file is D:\work\squad\model_save.zip, windows 10 system, browser: Microsoft Edge 44.17763.1.0)
> Hi, sorry for the late reply. Just asked another team member, the upload command doesn't work on Windows. Currently it seems no way to upload large files with Windows, which we are sorry about. We are working to see how to fix this problem. Can you find someone with Mac/linux to help you upload the bundle?
> 
> I has two systems on my computer, ubuntu is accessable. So how to upload large file using "cl upload path" command on ubuntu?
> 
> if it's home/file.zip, then setting path as ~/file.zip should work

my ubuntu is windows-wsl-ubuntu, there is no browser, is there any way to upload?

**Comment by hello-deh** [comment] 2019-12-18 02:42
> > > when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?
> > > There might be some problem uploading large files, I will get back to you after checking with the team, sorry for the inconvenience
> > > @yipenghe ,thank you for your reply , I  have uploaded files through CLI last week, it proved to be more useful . I have another question , can you suggest a good way to clear memory? I have deleted my worksheet, but there are  a lot bundles in my recent bundles list
> > > hello, Could you tell me how to use CLI: cl upload path, how to write "path" correctly? (suppose the local file is D:\work\squad\model_save.zip, windows 10 system, browser: Microsoft Edge 44.17763.1.0)
> > > Hi, sorry for the late reply. Just asked another team member, the upload command doesn't work on Windows. Currently it seems no way to upload large files with Windows, which we are sorry about. We are working to see how to fix this problem. Can you find someone with Mac/linux to help you upload the bundle?
> > 
> > 
> > I has two systems on my computer, ubuntu is accessable. So how to upload large file using "cl upload path" command on ubuntu?
> 
> if it's home/file.zip, then setting path as `~/file.zip` should work

On ubuntu system, firefox browser, 
cl upload /home/model_save.zip report error:
local file path not allowed without a filesystem.
How to solve ?

**Comment by hello-deh** [comment] 2019-12-19 14:15
> > when upload big files to codalab, the state always show uploading (for several days long), how to solve this problem?
> > There might be some problem uploading large files, I will get back to you after checking with the team, sorry for the inconvenience
> > @yipenghe ,thank you for your reply , I have uploaded files through CLI last week, it proved to be more useful . I have another question , can you suggest a good way to clear memory? I have deleted my worksheet, but there are a lot bundles in my recent bundles list
> > Great to know CLI worked, I think it might be related to how frontend handles file selection, I will test more after my finals.
> > For bulk deleting bundles, currently you would need to be on a worksheet that you have edit permission, I'm still thinking of a better logic to control this.
> > For now, I think the easiest way to remove a lot of bundles at once would be to:
> > create a new worksheet
> > copy the source on your dashboard (click 'view source' on top right) and paste in the new worksheet you just created (click edit source, paste and then save), you should now see checkboxes next to the bundle rows since you have edit permission on the newly created worksheet
> > bulk select all the bundles you want to delete, and click 'delete' on top left corner
> 
> thank you! It's a good method!

I have tried both on windows + edge browser and ubuntu system +firefox browser, but failed to upload files using cli ,like the following,
cl upload /home/model_save.zip report error:
local file path not allowed without a filesystem.
Do you know how to solve it ?

**Comment by Levilian** [comment] 2020-01-08 19:35
I uploaded a 1.7g file under 1.5 minute with the uploading status widget showing up on Safari, macOS

**Comment by Levilian** [comment] 2020-01-30 08:28
Cannot reproduce the bug - closing for now

**Closed as completed by Levilian** 2020-01-30 08:28 UTC
Labels: bug, frontend
