### ISSUE TITLE
InternalError: Blas SGEMM launch failed

### ISSUE THREAD

**Issue by rosecatherinek** [codalab/codalab-worksheets#392] opened 2017-12-06 21:30 UTC
We are getting a 'Blas SGEMM launch failed' error while trying to learn word2vec embeddings using Tensorflow. The code is pretty much the one in the TF tutorial (https://www.tensorflow.org/tutorials/word2vec). It runs without any problem on a regular GPU machine, but fails in the Codalab setup. 

The full error can be seen here:
https://codalab.rollme.ml.cmu.edu/bundles/0x3646a0f2dc614a6a971cbeadf753cf15/

I wonder if anyone else has faced this issue while running tf code in codalab and how they resolved it.

**Comment by fabeschan** [comment] 2017-12-07 20:02
I haven't seen this error personally when running tensorflow on codalab, but this error seems to be related to multiple consoles / processes occupying the same GPU

**Comment by connorbrinton** [comment] 2017-12-08 05:57
I've seen this running on CodaLab when other workers (on the same machine) were also using the GPU. It's probably another form of an out of memory error. There should be a line like this near the start of stderr:
```
totalMemory: 7.93GiB freeMemory: 83.06MiB
```
How much does yours show for `freeMemory`?

If this problem is the same as mine, then resolving #391 is the only real solution to this problem. However, you can hack around it by trying to launch multiple times, or not running too many jobs, to increase the probability that you get a machine without a GPU in use.

**Comment by rosecatherinek** [comment] 2017-12-10 19:48
Thanks @connorbrinton @fabeschan for your inputs. In this case, however, this particular machine was free - no process was running on any of its gpus. 

The logs in the link to codalab (in the first post) shows: 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
Total memory: 11.92GiB 
Free memory: 11.81GiB

However, there is this other error which we hadn't noticed at first: 

E tensorflow/stream_executor/cuda/cuda_blas.cc:372] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
W tensorflow/stream_executor/stream.cc:1390] attempting to perform BLAS operation using StreamExecutor without BLAS support

We are looking into that now. Thanks again!

**Comment by fabeschan** [comment] 2018-02-03 00:51
If you can, try to run the same task on nvidia-docker and see if you can reproduce the issue, as this is what codalab uses internally in order to talk to GPUs.

**Comment by bkgoksel** [comment] 2018-02-16 21:50
One reason for this error might be an issue in setting the LD_LIBRARY_PATH as in [this StackOverflow post](https://stackoverflow.com/questions/38303974/tensorflow-running-error-with-cublas)

**Comment by bkgoksel** [comment] 2018-02-23 19:47
Closing this until we get further indication that the problem might be codalab related

**Closed by bkgoksel** 2018-02-23 19:47 UTC
