### ISSUE TITLE
'cl run date' staged for a long time

### ISSUE THREAD

**Issue by mrctester** [codalab/codalab-worksheets#1099] opened 2019-03-18 02:09 UTC
Hello,
I tried to run `cl run date` and it showed `staged` status.
I waited for a long time (two days now!) and it didn't turn to `running` or `ready` status.
What is the main reason behind this?
Thank you.

**Comment by tbright17** [comment] 2019-03-18 17:14
Have the same problem here. Has been stuck at staged status for over one day. Please fix.

**Comment by LeejwUniverse** [comment] 2019-03-19 05:39
me too.. guys.
I could execute my prediction.json before a few days.
but now I can not show my evaluate score. why they're not working. please fix that.
especially, evaluation results are the Null status and data_size is marked as a null

**Comment by bkgoksel** [comment] 2019-03-19 06:29
Hi all,
We're investigating an ongoing issue on our systems at the moment. We're expecting everything to go back online in the next couple of hours. Depending on how the fix is applied you might need to re-run your bundles but ideally we'll avoid that situation. I'll keep this issue updated as we work on a fix.
Apologies for the error and thanks for your understanding.
Kerem from Codalab.

**Comment by bkgoksel** [comment] 2019-03-19 07:17
Hi all,
The issue is fixed. 
#1103 has a more detailed description of what went wrong. 

Your staged bundles should start running soon as our systems go through the backlog queue of bundles that accumulated over this outage. The only bundles we had to delete were from a single user who had a bunch of run bundles with the command `git clone`.

As reference, if you'd like to pull git repositories, the correct way to do so is to run
`cl up <URL of git repo e.g. https://github.com/codalab/codalab-worksheets> --git`
which should work for all publicly available git repositories.

**Closed as completed by bkgoksel** 2019-03-19 07:17 UTC

**Comment by tbright17** [comment] 2019-03-19 17:55
Thanks for the fix!

**Comment by tfzhou** [comment] 2019-06-12 10:24
It seems that the issue appears again!
