### ISSUE TITLE
web terminal doesn't work (perhaps due to Ubuntu 16.04)

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#553] opened 2016-08-03 15:02 UTC
All CLI commands work, but when `cl rm ^` or `cl run date` are typed into the web terminal, `Not authorized` is printed out, even when logged in.  `cl ls` does work though.  Noticed this after upgrading to Ubuntu 16.04.

**Comment by kashizui** [comment] 2016-08-03 19:17
Just installed my 16.04 VM so i'll get to play around with these new issues soon..

**Comment by kashizui** [comment] 2016-08-06 09:24
I'm able to reproduce this, but haven't figured out the cause yet.,

**Comment by kashizui** [comment] 2016-08-06 23:55
This bug doesn't seem limited to Ubuntu 16, I'm getting it on mac as well.

**Comment by kashizui** [comment] 2016-08-07 01:03
This issue doesn't occur on `master`, only `develop`, so that may give us a hint.

**Comment by kashizui** [comment] 2016-08-07 08:26
Fixed by #559

**Closed as completed** 2016-08-17 04:46 UTC
Labels: bug
