### ISSUE TITLE
[USER ISSUE] download timeout

### ISSUE THREAD

**Issue by RaymondLi0** [codalab/codalab-worksheets#3071] opened 2020-11-18 00:51 UTC
**Describe the bug**
There is a timeout when downloading a bundle. The bundle's size is 4.3 GB

**Codalab Information**
- *Your username*: Raymond
- *UUID of problem bundle (please don't delete)*: 0x1421494fb6814e45b74dd072a794e548
- *Error message received from Codalab (if applicable)*:
```
Failed to download dependency model_best_checkpoint: Dependency download failed: Unable to get bundle contents from bundle service: The read operation timed out
```

In the past I managed to use bundles of similar size, I'm wondering why this fails now.

**Comment by Winggi** [comment] 2020-11-19 19:21
I am suffering from this problem too...

**Comment by Winggi** [comment] 2020-11-19 19:25
The same files and command. It worked half a year ago, but now I get this error.

**Comment by epicfaace** [comment] 2020-11-20 17:23
This will be fixed in the upcoming release (#3045).

**Comment by Winggi** [comment] 2020-11-20 17:29
> This will be fixed in the upcoming release (#3045).

Great! By the way, is there any method that can solve it if I need to run my bundle urgently?

**Comment by epicfaace** [comment] 2020-11-20 20:39
Maybe try requesting memory greater than 4.3 GB? The issue is that the bundle contents have to all fit in memory, or this bug will occur.

**Comment by RaymondLi0** [comment] 2020-11-25 19:15
Thanks for the release! It indeed fixes this issue.

However downloading a bundle this size takes 6 hours right now. This is impractical to work with. Is there a way around this?

**Comment by epicfaace** [comment] 2020-12-04 15:08
Hmm, did it take that long in the past? How long did it take earlier?

Could this have to do with your network speed, perhaps, or are you sure it's an issue with CodaLab?

**Comment by epicfaace** [comment] 2020-12-04 20:08
It does appear to be an issue that others are facing -- probably because the server has been getting slower after the latest release. We'll look into it

**Comment by epicfaace** [comment] 2020-12-04 20:24
Merging this new issue into #3092.

**Closed as completed by epicfaace** 2020-12-04 20:24 UTC
Labels: user-question, p1
