### ISSUE TITLE
show docker download status

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#3175] opened 2021-01-12 05:47 UTC
Currently, the `run_status` is stuck in `Pulling docker image: Download starting.` for a very long time and it's not clear what's happening.  We used to show the progress of the docker download, but it disappeared during a refactor.  It'd be nice to get it back.

**Comment by epicfaace** [comment] 2021-01-14 22:04
Duplicate of #3174

**Closed as completed by epicfaace** 2021-01-14 22:04 UTC
Labels: backend, p1
