### ISSUE TITLE
 Prevent multiple people from editing and clobbering changes: if

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#7] opened 2015-12-27 10:09 UTC
<a href="https://github.com/Raisins"><img src="https://avatars.githubusercontent.com/u/123099?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Raisins](https://github.com/Raisins)**
_Friday Jan 16, 2015 at 18:27 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/828_

----

 Prevent multiple people from editing and clobbering changes: if start editing, and in the meantime someone already saved the worksheet, then try to save, system should throw an error rather than clobber their changes: this is already done on the CLI (remember not to throw away the changes in the text box!)

**Comment by codalab** [comment] 2015-12-27 10:09
<a href="https://github.com/Raisins"><img src="https://avatars.githubusercontent.com/u/123099?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Raisins](https://github.com/Raisins)**
_Wednesday Mar 04, 2015 at 23:40 GMT_

----

this comment was on wrong issue

Traced though this. I am calling the same functions as the cli in the same order not getting the UsageError There is something deeper with saving going on. This will take more time then originally thought.

**Comment by codalab** [comment] 2015-12-27 10:09
<a href="https://github.com/ErickWa"><img src="https://avatars.githubusercontent.com/u/4361560?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ErickWa](https://github.com/ErickWa)**
_Thursday Mar 19, 2015 at 17:37 GMT_

----

Dependencies on CLI behavior - need Percy's help - moving to April

**Comment by percyliang** [comment] 2015-12-29 06:04
Duplicate of #16

**Closed by percyliang** 2015-12-29 06:04 UTC
