### ISSUE TITLE
Make sure all content is viewable by people and search engine

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1056] opened 2019-03-11 05:49 UTC
_From @maxwang7 on December 4, 2017 1:54_

_Copied from original issue: codalab/codalab-worksheets#390_

**Comment by w0nche0l** [comment] 2019-03-11 05:49
_From @percyliang on December 26, 2017 4:30_

Just need to make sure we have an infinite scrolling list of bundles/worksheets/users (ordered from most recent) so that a search engine can crawl it and index everything.  Backend can just use (`cl search` and `cl wsearch`).

**Comment by epicfaace** [comment] 2021-06-25 19:43
closing as duplicate of https://github.com/codalab/codalab-worksheets/issues/2592

**Closed as completed by epicfaace** 2021-06-25 19:43 UTC
Labels: feature, frontend, p3
