### ISSUE TITLE
can't append items to worksheet

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2667] opened 2020-07-28 04:12 UTC
Go to the last item of the worksheet.  Add text or add a run.  It shows up as the second to last item rather than the last item.

**Comment by yipenghe** [comment] 2020-07-28 04:23
I think it's the same as what this fix: https://github.com/codalab/codalab-worksheets/pull/2588
It's not included in 0.5.20 though

**Comment by epicfaace** [comment] 2020-07-28 12:32
Let's close this as a duplicate of #2588 then.

**Closed as completed by epicfaace** 2020-07-28 12:32 UTC
Labels: bug, frontend
