### ISSUE TITLE
Command+Click on worksheet link opens current worksheet and the linked worksheet

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2763] opened 2020-08-16 23:11 UTC
Command+click generally opens the link in a new tab, without switching focus to it. However, when command+click ing on a worksheet link, 2 new tabs open.

Video with demonstration: https://streamable.com/wxailm

**Comment by epicfaace** [comment] 2020-08-17 01:33
Duplicate of #2617 (great video though!)

**Closed as completed by epicfaace** 2020-08-17 01:33 UTC
Labels: user-question
