### ISSUE TITLE
[USER ISSUE] competitiond script throwing "Could not find worksheet with uuid None" error

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#1910] opened 2020-01-17 22:53 UTC
**Describe the bug**
The competitiond.py script is throwing an error unexpectedly. This is preventing me from updating the SQuAD 2.0 leaderboard.

**Codalab Information**
- *Your username*: robinjia
- *UUID of worksheet where problem occurred*: 
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:
I printed out the traceback and you see many things like the following:

[INFO] 2020-01-17 14:48:20,727: Mimicking submission for fuzixi
Traceback (most recent call last):
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 15, in wrapper
    return f(*args, **kwargs)
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 463, in create
    data=self._pack_document(data if isinstance(data, list) else [data], resource_type),
  File "./scripts/competitiond.py", line 74, in _make_request
    return super(JsonApiClientWithRetry, self)._make_request(*args, **kwargs)
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/worker/rest_client.py", line 98, in _make_request
    with closing(urllib.request.urlopen(request)) as response:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/competitiond.py", line 740, in run_once
    predict_bundle = self.run_prediction(submit_bundle)
  File "./scripts/competitiond.py", line 484, in run_prediction
    predict_bundle = find_mimicked(mimic_bundles(dry_run=False, **mimic_args))
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/lib/bundle_util.py", line 284, in mimic_bundles
    'bundle': JsonApiRelationship('bundles', new_bundle_uuid),
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 22, in wrapper
    six.reraise(exc.__class__, exc, sys.exc_info()[2])
  File "/home/robinjia/.local/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 15, in wrapper
    return f(*args, **kwargs)
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 463, in create
    data=self._pack_document(data if isinstance(data, list) else [data], resource_type),
  File "./scripts/competitiond.py", line 74, in _make_request
    return super(JsonApiClientWithRetry, self)._make_request(*args, **kwargs)
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/worker/rest_client.py", line 98, in _make_request
    with closing(urllib.request.urlopen(request)) as response:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
codalab.common.NotFoundError: Could not find worksheet with uuid None

As a result of this, no run bundles are created when I expect them to be created.

 - *OS (if on CLI)*: Ubuntu 18.04
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

I ran `python3 ./scripts/competitiond.py -v ../config/codalab-v2.0.json ../out-v2.0.json` using my config files (e.g. https://github.com/rajpurkar/SQuAD-explorer/blob/master/config/codalab-v2.0.json)

**Expected behavior**

**Screenshots**

**Additional context**
I'm happy to discuss this in person, I think with this would be hard for someone else to reproduce directly (I think it would try to rerun all of the SQuAD submissions or something)

**Comment by candicegjing** [comment] 2020-01-18 00:11
I am able to reproduce this issue but with a slightly different one. See the following error message:
```
[INFO] 2020-01-17 16:08:45,922: Running batch competition evaluation
[DEBUG] 2020-01-17 16:08:47,529: Collecting latest submissions
[INFO] 2020-01-17 16:08:55,680: Mimicking submission for robinjia
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 15, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 414, in fetch
    query_params=self._pack_params(params),
  File "competitiond.py", line 74, in _make_request
    return super(JsonApiClientWithRetry, self)._make_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/codalab/worker/rest_client.py", line 98, in _make_request
    with closing(urllib.request.urlopen(request)) as response:
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "competitiond.py", line 845, in <module>
    main()
  File "competitiond.py", line 841, in main
    comp.run_once()
  File "competitiond.py", line 735, in run_once
    predict_bundle = self.run_prediction(submit_bundle)
  File "competitiond.py", line 473, in run_prediction
    if find_mimicked(mimic_bundles(dry_run=True, **mimic_args)) is None:
  File "/usr/local/lib/python3.7/site-packages/codalab/lib/bundle_util.py", line 115, in mimic_bundles
    all_bundle_uuids = get_self_and_ancestors(list(infos.keys()))
  File "/usr/local/lib/python3.7/site-packages/codalab/lib/bundle_util.py", line 96, in get_self_and_ancestors
    infos[bundle_uuid] = client.fetch('bundles', bundle_uuid)
  File "/usr/local/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 22, in wrapper
    six.reraise(exc.__class__, exc, sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 15, in wrapper
    return f(*args, **kwargs)
......
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
codalab.common.NotFoundError: b'Bundle 0x15a09c8f74f94a20bec0b68a2e6703b3 not found'
```
It's complaining for a bundle 0x15a09c8f74f94a20bec0b68a2e6703b3 that doesn't exist any more.

**Comment by robinjia** [comment] 2020-01-18 00:22
Ah yeah that is expected. I did not mention that I actually modified the competitiond.py script slightly: in line 735 I surrounded the `predict_bundle = self.run_prediction(submit_bundle)` line with a try/catch and just skip over errors. This is because some SQuAD submissions have various issues that make them not runnable. However this "could not find worksheet" error just started happening to many submissions, and I don't think it's due to submissions being badly formatted.

**Comment by candicegjing** [comment] 2020-01-18 00:26
@robinjia Can you share the modification you made on line 735?

**Comment by robinjia** [comment] 2020-01-18 00:27
Replace it with

```
                try:
                    predict_bundle = self.run_prediction(submit_bundle)
                except Exception as e:
                    traceback.print_exc()
                    continue
```

**Comment by candicegjing** [comment] 2020-01-18 00:53
@robinjia I submitted a bunch of jobs but don't see the error `Could not find worksheet with uuid None`. All the errors that happened on my side are due to a specific bundle not found. 
Is there any other modification I need to make in order to reproduce the error? Or is this only happened for `fuzixi`?

**Comment by robinjia** [comment] 2020-01-18 01:05
That is the only change to the competitiond.py script, and I have pulled my repo to sync with master.

I see the error for 5 submissions: hraw, huahua, thunthersine88 twice, and fuzixi

**Comment by candicegjing** [comment] 2020-01-18 01:26
I just submitted 3 jobs for `fuzixi`:
https://worksheets.codalab.org/bundles/0xd0accc6114fe48a4bf59f4f797c685b4
https://worksheets.codalab.org/bundles/0x3c86b69f513d4ae1b680203fba47938f
https://worksheets.codalab.org/bundles/0xaf18ba14f9064bc994fc3f2a9a9e1802
They seem to be looking fine. I am checking others.

**Comment by robinjia** [comment] 2020-01-18 02:09
Hmm that is interesting. Do you think it could have to do with using my login credentials instead of yours?

**Comment by candicegjing** [comment] 2020-01-18 17:04
I doubt that. Is this happen repetitively or just once? Do you still see this error?

**Comment by robinjia** [comment] 2020-01-18 21:09
This happens repeatedly (I just tried it and the same error still happens).

**Comment by candicegjing** [comment] 2020-01-19 18:41
@robinjia If possible, maybe I can borrow your account and investigate this issue?

**Comment by robinjia** [comment] 2020-01-20 06:14
Sure, how can I help?

**Comment by candicegjing** [comment] 2020-01-21 20:17
@robinjia I am at Gates this afternoon. Let me know when you will be here, then I can borrow your account directly.

**Comment by candicegjing** [comment] 2020-01-22 01:25
Reran the scripts using @robinjia's account on my machines. Jobs are able to proceed without an error. @robinjia will upgrade to the latest codalab package and rerun the competition script.

**Comment by candicegjing** [comment] 2020-01-22 21:35
@robinjia upgraded the package and then the error went away. Closing this ticket now.

**Closed as completed by candicegjing** 2020-01-22 21:35 UTC
Labels: user-question
